"""Curated Deep Sky Object catalog — base targets + solar system objects.
Additional Messier, Caldwell, and popular targets are in expanded_catalog.py."""

DSO_CATALOG = [
    # ═══ WINTER — Emission Nebulae ═══
    {"name": "Orion Nebula", "catalog_id": "M42", "alt_catalog_ids": "NGC 1976",
     "target_type": "Emission Nebula", "ra_hours": 5.588, "dec_degrees": -5.39,
     "magnitude": 4.0, "size_arcmin": 85, "size_arcmin_minor": 60,
     "constellation": "Orion", "season": "Winter", "difficulty": "Easy",
     "recommended_min_hours": 3, "narrowband_target": True, "broadband_target": True,
     "description": "The Great Orion Nebula — brightest nebula, stunning at any focal length."},
    {"name": "Running Man Nebula", "catalog_id": "NGC 1977", "alt_catalog_ids": "Sh2-279",
     "target_type": "Reflection Nebula", "ra_hours": 5.586, "dec_degrees": -4.84,
     "magnitude": 7.0, "size_arcmin": 40, "size_arcmin_minor": 25,
     "constellation": "Orion", "season": "Winter", "difficulty": "Moderate",
     "recommended_min_hours": 6, "narrowband_target": False, "broadband_target": True,
     "description": "Reflection nebula adjacent to M42. Best framed together."},
    {"name": "Horsehead Nebula", "catalog_id": "B33", "alt_catalog_ids": "IC 434",
     "target_type": "Dark Nebula", "ra_hours": 5.681, "dec_degrees": -2.46,
     "magnitude": None, "size_arcmin": 8, "size_arcmin_minor": 6,
     "constellation": "Orion", "season": "Winter", "difficulty": "Hard",
     "recommended_min_hours": 10, "narrowband_target": True, "broadband_target": True,
     "description": "Iconic dark nebula silhouetted against IC 434. Pair with Flame Nebula."},
    {"name": "Flame Nebula", "catalog_id": "NGC 2024", "alt_catalog_ids": "Sh2-277",
     "target_type": "Emission Nebula", "ra_hours": 5.679, "dec_degrees": -1.84,
     "magnitude": None, "size_arcmin": 30, "size_arcmin_minor": 30,
     "constellation": "Orion", "season": "Winter", "difficulty": "Moderate",
     "recommended_min_hours": 6, "narrowband_target": True, "broadband_target": True,
     "description": "Bright emission nebula near Alnitak. Excellent with Horsehead."},
    {"name": "Rosette Nebula", "catalog_id": "NGC 2237", "alt_catalog_ids": "Caldwell 49, Sh2-275",
     "target_type": "Emission Nebula", "ra_hours": 6.534, "dec_degrees": 4.95,
     "magnitude": 9.0, "size_arcmin": 80, "size_arcmin_minor": 60,
     "constellation": "Monoceros", "season": "Winter", "difficulty": "Moderate",
     "recommended_min_hours": 6, "narrowband_target": True, "broadband_target": True,
     "description": "Spectacular flower-shaped emission nebula. Great for wide field."},
    {"name": "Cone Nebula", "catalog_id": "NGC 2264", "alt_catalog_ids": "Christmas Tree Cluster",
     "target_type": "Emission Nebula", "ra_hours": 6.681, "dec_degrees": 9.89,
     "magnitude": 3.9, "size_arcmin": 40, "size_arcmin_minor": 30,
     "constellation": "Monoceros", "season": "Winter", "difficulty": "Moderate",
     "recommended_min_hours": 8, "narrowband_target": True, "broadband_target": True,
     "description": "Dark cone shape with Christmas Tree cluster."},
    {"name": "Monkey Head Nebula", "catalog_id": "NGC 2174", "alt_catalog_ids": "Sh2-252",
     "target_type": "Emission Nebula", "ra_hours": 6.163, "dec_degrees": 20.49,
     "magnitude": 6.8, "size_arcmin": 40, "size_arcmin_minor": 30,
     "constellation": "Orion", "season": "Winter", "difficulty": "Moderate",
     "recommended_min_hours": 6, "narrowband_target": True, "broadband_target": True,
     "description": "Colorful emission nebula with dark lanes and pillars."},
    {"name": "Thor's Helmet", "catalog_id": "NGC 2359", "alt_catalog_ids": "Sh2-298",
     "target_type": "Emission Nebula", "ra_hours": 7.303, "dec_degrees": -13.19,
     "magnitude": 11.5, "size_arcmin": 10, "size_arcmin_minor": 10,
     "constellation": "Canis Major", "season": "Winter", "difficulty": "Moderate",
     "recommended_min_hours": 8, "narrowband_target": True, "broadband_target": False,
     "description": "Wolf-Rayet bubble nebula. Best in narrowband."},
    {"name": "Jellyfish Nebula", "catalog_id": "IC 443", "alt_catalog_ids": "Sh2-248",
     "target_type": "Supernova Remnant", "ra_hours": 6.283, "dec_degrees": 22.47,
     "magnitude": None, "size_arcmin": 50, "size_arcmin_minor": 40,
     "constellation": "Gemini", "season": "Winter", "difficulty": "Hard",
     "recommended_min_hours": 12, "narrowband_target": True, "broadband_target": False,
     "description": "Faint supernova remnant. Requires significant narrowband integration."},
    {"name": "Crab Nebula", "catalog_id": "M1", "alt_catalog_ids": "NGC 1952",
     "target_type": "Supernova Remnant", "ra_hours": 5.575, "dec_degrees": 22.01,
     "magnitude": 8.4, "size_arcmin": 6, "size_arcmin_minor": 4,
     "constellation": "Taurus", "season": "Winter", "difficulty": "Easy",
     "recommended_min_hours": 4, "narrowband_target": True, "broadband_target": True,
     "description": "Compact, bright supernova remnant."},
    {"name": "Pleiades", "catalog_id": "M45", "alt_catalog_ids": "Seven Sisters",
     "target_type": "Open Cluster", "ra_hours": 3.788, "dec_degrees": 24.12,
     "magnitude": 1.6, "size_arcmin": 110, "size_arcmin_minor": 110,
     "constellation": "Taurus", "season": "Winter", "difficulty": "Easy",
     "recommended_min_hours": 4, "narrowband_target": False, "broadband_target": True,
     "description": "Brilliant open cluster with reflection nebulosity."},
    {"name": "California Nebula", "catalog_id": "NGC 1499", "alt_catalog_ids": "Sh2-220",
     "target_type": "Emission Nebula", "ra_hours": 4.050, "dec_degrees": 36.37,
     "magnitude": None, "size_arcmin": 145, "size_arcmin_minor": 40,
     "constellation": "Perseus", "season": "Winter", "difficulty": "Moderate",
     "recommended_min_hours": 8, "narrowband_target": True, "broadband_target": False,
     "description": "Very large, faint emission nebula. Needs wide FOV and narrowband."},
    {"name": "Flaming Star Nebula", "catalog_id": "IC 405", "alt_catalog_ids": "Sh2-229",
     "target_type": "Emission Nebula", "ra_hours": 5.271, "dec_degrees": 34.27,
     "magnitude": None, "size_arcmin": 30, "size_arcmin_minor": 19,
     "constellation": "Auriga", "season": "Winter", "difficulty": "Moderate",
     "recommended_min_hours": 8, "narrowband_target": True, "broadband_target": True,
     "description": "Emission and reflection nebula around AE Aurigae."},
    {"name": "Tadpole Nebula", "catalog_id": "IC 410", "alt_catalog_ids": "Sh2-236",
     "target_type": "Emission Nebula", "ra_hours": 5.433, "dec_degrees": 33.39,
     "magnitude": None, "size_arcmin": 40, "size_arcmin_minor": 30,
     "constellation": "Auriga", "season": "Winter", "difficulty": "Moderate",
     "recommended_min_hours": 8, "narrowband_target": True, "broadband_target": True,
     "description": "Emission nebula with distinctive tadpole-shaped structures."},
    {"name": "Soul Nebula", "catalog_id": "IC 1848", "alt_catalog_ids": "Sh2-199",
     "target_type": "Emission Nebula", "ra_hours": 2.867, "dec_degrees": 60.45,
     "magnitude": None, "size_arcmin": 150, "size_arcmin_minor": 75,
     "constellation": "Cassiopeia", "season": "Winter", "difficulty": "Moderate",
     "recommended_min_hours": 8, "narrowband_target": True, "broadband_target": False,
     "description": "Large emission nebula. Partner to the Heart Nebula."},
    {"name": "Heart Nebula", "catalog_id": "IC 1805", "alt_catalog_ids": "Sh2-190",
     "target_type": "Emission Nebula", "ra_hours": 2.540, "dec_degrees": 61.47,
     "magnitude": None, "size_arcmin": 150, "size_arcmin_minor": 150,
     "constellation": "Cassiopeia", "season": "Winter", "difficulty": "Moderate",
     "recommended_min_hours": 8, "narrowband_target": True, "broadband_target": False,
     "description": "Heart-shaped emission nebula. Best with narrowband at short FL."},
    {"name": "Pac-Man Nebula", "catalog_id": "NGC 281", "alt_catalog_ids": "IC 11, Sh2-184",
     "target_type": "Emission Nebula", "ra_hours": 0.883, "dec_degrees": 56.62,
     "magnitude": 7.4, "size_arcmin": 35, "size_arcmin_minor": 30,
     "constellation": "Cassiopeia", "season": "Winter", "difficulty": "Moderate",
     "recommended_min_hours": 6, "narrowband_target": True, "broadband_target": True,
     "description": "Distinctive shape with dark Bok globules."},
    {"name": "Seagull Nebula", "catalog_id": "IC 2177", "alt_catalog_ids": "Sh2-296",
     "target_type": "Emission Nebula", "ra_hours": 7.063, "dec_degrees": -10.42,
     "magnitude": None, "size_arcmin": 120, "size_arcmin_minor": 40,
     "constellation": "Monoceros", "season": "Winter", "difficulty": "Moderate",
     "recommended_min_hours": 8, "narrowband_target": True, "broadband_target": True,
     "description": "Very large bird-shaped nebula."},

    # ═══ SPRING — Galaxies ═══
    {"name": "Bode's Galaxy & Cigar Galaxy", "catalog_id": "M81/M82", "alt_catalog_ids": "NGC 3031/3034",
     "target_type": "Galaxy Group", "ra_hours": 9.926, "dec_degrees": 69.07,
     "magnitude": 6.9, "size_arcmin": 27, "size_arcmin_minor": 14,
     "constellation": "Ursa Major", "season": "Spring", "difficulty": "Easy",
     "recommended_min_hours": 4, "narrowband_target": False, "broadband_target": True,
     "description": "Classic galaxy pair. M82 shows dramatic hydrogen outflows."},
    {"name": "Leo Triplet", "catalog_id": "M65/M66/NGC 3628", "alt_catalog_ids": "",
     "target_type": "Galaxy Group", "ra_hours": 11.318, "dec_degrees": 13.07,
     "magnitude": 8.9, "size_arcmin": 50, "size_arcmin_minor": 35,
     "constellation": "Leo", "season": "Spring", "difficulty": "Moderate",
     "recommended_min_hours": 6, "narrowband_target": False, "broadband_target": True,
     "description": "Three galaxies in one FOV. NGC 3628 has tidal tail."},
    {"name": "Pinwheel Galaxy", "catalog_id": "M101", "alt_catalog_ids": "NGC 5457",
     "target_type": "Spiral Galaxy", "ra_hours": 14.054, "dec_degrees": 54.35,
     "magnitude": 7.9, "size_arcmin": 29, "size_arcmin_minor": 27,
     "constellation": "Ursa Major", "season": "Spring", "difficulty": "Moderate",
     "recommended_min_hours": 6, "narrowband_target": False, "broadband_target": True,
     "description": "Face-on spiral galaxy with HII regions in arms."},
    {"name": "Whirlpool Galaxy", "catalog_id": "M51", "alt_catalog_ids": "NGC 5194/5195",
     "target_type": "Spiral Galaxy", "ra_hours": 13.498, "dec_degrees": 47.20,
     "magnitude": 8.4, "size_arcmin": 11, "size_arcmin_minor": 7,
     "constellation": "Canes Venatici", "season": "Spring", "difficulty": "Easy",
     "recommended_min_hours": 4, "narrowband_target": False, "broadband_target": True,
     "description": "Interacting face-on spiral. Iconic target at moderate FL."},
    {"name": "Markarian's Chain", "catalog_id": "M84/M86+", "alt_catalog_ids": "Virgo Cluster",
     "target_type": "Galaxy Group", "ra_hours": 12.448, "dec_degrees": 12.89,
     "magnitude": 9.1, "size_arcmin": 90, "size_arcmin_minor": 20,
     "constellation": "Virgo", "season": "Spring", "difficulty": "Moderate",
     "recommended_min_hours": 6, "narrowband_target": False, "broadband_target": True,
     "description": "Chain of galaxies in the Virgo Cluster."},
    {"name": "Needle Galaxy", "catalog_id": "NGC 4565", "alt_catalog_ids": "Caldwell 38",
     "target_type": "Spiral Galaxy", "ra_hours": 12.604, "dec_degrees": 25.99,
     "magnitude": 10.4, "size_arcmin": 16, "size_arcmin_minor": 2,
     "constellation": "Coma Berenices", "season": "Spring", "difficulty": "Moderate",
     "recommended_min_hours": 6, "narrowband_target": False, "broadband_target": True,
     "description": "Perfect edge-on spiral with prominent dust lane."},
    {"name": "Sombrero Galaxy", "catalog_id": "M104", "alt_catalog_ids": "NGC 4594",
     "target_type": "Spiral Galaxy", "ra_hours": 12.666, "dec_degrees": -11.62,
     "magnitude": 8.0, "size_arcmin": 9, "size_arcmin_minor": 4,
     "constellation": "Virgo", "season": "Spring", "difficulty": "Easy",
     "recommended_min_hours": 4, "narrowband_target": False, "broadband_target": True,
     "description": "Bright galaxy with dramatic dust lane."},
    {"name": "Black Eye Galaxy", "catalog_id": "M64", "alt_catalog_ids": "NGC 4826",
     "target_type": "Spiral Galaxy", "ra_hours": 12.944, "dec_degrees": 21.68,
     "magnitude": 8.5, "size_arcmin": 10, "size_arcmin_minor": 5,
     "constellation": "Coma Berenices", "season": "Spring", "difficulty": "Easy",
     "recommended_min_hours": 4, "narrowband_target": False, "broadband_target": True,
     "description": "Distinctive dark dust feature."},
    {"name": "Sunflower Galaxy", "catalog_id": "M63", "alt_catalog_ids": "NGC 5055",
     "target_type": "Spiral Galaxy", "ra_hours": 13.264, "dec_degrees": 42.03,
     "magnitude": 8.6, "size_arcmin": 13, "size_arcmin_minor": 8,
     "constellation": "Canes Venatici", "season": "Spring", "difficulty": "Moderate",
     "recommended_min_hours": 6, "narrowband_target": False, "broadband_target": True,
     "description": "Flocculent spiral with subtle arm structure."},
    {"name": "Andromeda Galaxy", "catalog_id": "M31", "alt_catalog_ids": "NGC 224",
     "target_type": "Spiral Galaxy", "ra_hours": 0.712, "dec_degrees": 41.27,
     "magnitude": 3.4, "size_arcmin": 190, "size_arcmin_minor": 60,
     "constellation": "Andromeda", "season": "Autumn", "difficulty": "Easy",
     "recommended_min_hours": 4, "narrowband_target": False, "broadband_target": True,
     "description": "Nearest large galaxy. Enormous — needs very wide FOV or mosaic."},
    {"name": "Triangulum Galaxy", "catalog_id": "M33", "alt_catalog_ids": "NGC 598",
     "target_type": "Spiral Galaxy", "ra_hours": 1.565, "dec_degrees": 30.66,
     "magnitude": 5.7, "size_arcmin": 73, "size_arcmin_minor": 45,
     "constellation": "Triangulum", "season": "Autumn", "difficulty": "Moderate",
     "recommended_min_hours": 6, "narrowband_target": True, "broadband_target": True,
     "description": "Face-on spiral with bright HII regions."},
    {"name": "NGC 891", "catalog_id": "NGC 891", "alt_catalog_ids": "Caldwell 23",
     "target_type": "Spiral Galaxy", "ra_hours": 2.376, "dec_degrees": 42.35,
     "magnitude": 10.8, "size_arcmin": 14, "size_arcmin_minor": 3,
     "constellation": "Andromeda", "season": "Autumn", "difficulty": "Moderate",
     "recommended_min_hours": 6, "narrowband_target": False, "broadband_target": True,
     "description": "Beautiful edge-on spiral with prominent central dust lane."},

    # ═══ SUMMER — Emission Nebulae ═══
    {"name": "Eagle Nebula", "catalog_id": "M16", "alt_catalog_ids": "NGC 6611",
     "target_type": "Emission Nebula", "ra_hours": 18.314, "dec_degrees": -13.79,
     "magnitude": 6.0, "size_arcmin": 35, "size_arcmin_minor": 28,
     "constellation": "Serpens", "season": "Summer", "difficulty": "Easy",
     "recommended_min_hours": 4, "narrowband_target": True, "broadband_target": True,
     "description": "Pillars of Creation! Gorgeous in narrowband and broadband."},
    {"name": "Omega/Swan Nebula", "catalog_id": "M17", "alt_catalog_ids": "NGC 6618",
     "target_type": "Emission Nebula", "ra_hours": 18.346, "dec_degrees": -16.17,
     "magnitude": 6.0, "size_arcmin": 40, "size_arcmin_minor": 30,
     "constellation": "Sagittarius", "season": "Summer", "difficulty": "Easy",
     "recommended_min_hours": 4, "narrowband_target": True, "broadband_target": True,
     "description": "Bright emission nebula with checkmark shape."},
    {"name": "Lagoon Nebula", "catalog_id": "M8", "alt_catalog_ids": "NGC 6523",
     "target_type": "Emission Nebula", "ra_hours": 18.063, "dec_degrees": -24.38,
     "magnitude": 6.0, "size_arcmin": 90, "size_arcmin_minor": 40,
     "constellation": "Sagittarius", "season": "Summer", "difficulty": "Easy",
     "recommended_min_hours": 4, "narrowband_target": True, "broadband_target": True,
     "description": "Large, bright nebula. Low altitude from 40N."},
    {"name": "Trifid Nebula", "catalog_id": "M20", "alt_catalog_ids": "NGC 6514",
     "target_type": "Emission Nebula", "ra_hours": 18.043, "dec_degrees": -23.03,
     "magnitude": 6.3, "size_arcmin": 28, "size_arcmin_minor": 28,
     "constellation": "Sagittarius", "season": "Summer", "difficulty": "Easy",
     "recommended_min_hours": 4, "narrowband_target": True, "broadband_target": True,
     "description": "Three-lobed nebula with emission, reflection, and dark components."},
    {"name": "North America Nebula", "catalog_id": "NGC 7000", "alt_catalog_ids": "Caldwell 20",
     "target_type": "Emission Nebula", "ra_hours": 20.988, "dec_degrees": 44.33,
     "magnitude": None, "size_arcmin": 120, "size_arcmin_minor": 100,
     "constellation": "Cygnus", "season": "Summer", "difficulty": "Moderate",
     "recommended_min_hours": 6, "narrowband_target": True, "broadband_target": False,
     "description": "Enormous emission nebula shaped like North America."},
    {"name": "Pelican Nebula", "catalog_id": "IC 5070", "alt_catalog_ids": "",
     "target_type": "Emission Nebula", "ra_hours": 20.837, "dec_degrees": 44.35,
     "magnitude": None, "size_arcmin": 60, "size_arcmin_minor": 50,
     "constellation": "Cygnus", "season": "Summer", "difficulty": "Moderate",
     "recommended_min_hours": 6, "narrowband_target": True, "broadband_target": False,
     "description": "Partner to North America Nebula."},
    {"name": "Veil Nebula (Eastern)", "catalog_id": "NGC 6992", "alt_catalog_ids": "Caldwell 33",
     "target_type": "Supernova Remnant", "ra_hours": 20.941, "dec_degrees": 31.72,
     "magnitude": 7.0, "size_arcmin": 60, "size_arcmin_minor": 8,
     "constellation": "Cygnus", "season": "Summer", "difficulty": "Moderate",
     "recommended_min_hours": 6, "narrowband_target": True, "broadband_target": True,
     "description": "Brilliant filamentary supernova remnant. Stunning in OIII."},
    {"name": "Veil Nebula (Western)", "catalog_id": "NGC 6960", "alt_catalog_ids": "Caldwell 34",
     "target_type": "Supernova Remnant", "ra_hours": 20.756, "dec_degrees": 30.71,
     "magnitude": 7.0, "size_arcmin": 70, "size_arcmin_minor": 6,
     "constellation": "Cygnus", "season": "Summer", "difficulty": "Moderate",
     "recommended_min_hours": 6, "narrowband_target": True, "broadband_target": True,
     "description": "Western arc of Veil complex."},
    {"name": "Elephant's Trunk Nebula", "catalog_id": "IC 1396", "alt_catalog_ids": "Sh2-131",
     "target_type": "Emission Nebula", "ra_hours": 21.651, "dec_degrees": 57.50,
     "magnitude": 3.5, "size_arcmin": 170, "size_arcmin_minor": 140,
     "constellation": "Cepheus", "season": "Summer", "difficulty": "Moderate",
     "recommended_min_hours": 8, "narrowband_target": True, "broadband_target": False,
     "description": "Huge emission nebula with famous dark trunk feature."},
    {"name": "Crescent Nebula", "catalog_id": "NGC 6888", "alt_catalog_ids": "Sh2-105",
     "target_type": "Emission Nebula", "ra_hours": 20.200, "dec_degrees": 38.35,
     "magnitude": 7.4, "size_arcmin": 18, "size_arcmin_minor": 12,
     "constellation": "Cygnus", "season": "Summer", "difficulty": "Moderate",
     "recommended_min_hours": 8, "narrowband_target": True, "broadband_target": False,
     "description": "Wolf-Rayet wind-blown bubble. Best in narrowband."},
    {"name": "Bubble Nebula", "catalog_id": "NGC 7635", "alt_catalog_ids": "Sh2-162",
     "target_type": "Emission Nebula", "ra_hours": 23.348, "dec_degrees": 61.20,
     "magnitude": 10.0, "size_arcmin": 15, "size_arcmin_minor": 8,
     "constellation": "Cassiopeia", "season": "Summer", "difficulty": "Moderate",
     "recommended_min_hours": 8, "narrowband_target": True, "broadband_target": False,
     "description": "Wind-blown bubble nebula. Excellent in Ha/OIII."},
    {"name": "Cocoon Nebula", "catalog_id": "IC 5146", "alt_catalog_ids": "Sh2-125",
     "target_type": "Emission Nebula", "ra_hours": 21.893, "dec_degrees": 47.27,
     "magnitude": 7.2, "size_arcmin": 12, "size_arcmin_minor": 12,
     "constellation": "Cygnus", "season": "Summer", "difficulty": "Moderate",
     "recommended_min_hours": 8, "narrowband_target": True, "broadband_target": True,
     "description": "Compact emission nebula at end of dark nebula Barnard 168."},
    {"name": "Cave Nebula", "catalog_id": "Sh2-155", "alt_catalog_ids": "Caldwell 9",
     "target_type": "Emission Nebula", "ra_hours": 22.953, "dec_degrees": 62.62,
     "magnitude": None, "size_arcmin": 50, "size_arcmin_minor": 30,
     "constellation": "Cepheus", "season": "Summer", "difficulty": "Hard",
     "recommended_min_hours": 10, "narrowband_target": True, "broadband_target": False,
     "description": "Faint emission nebula with dark cave-like structure."},

    # ═══ SUMMER — Planetary Nebulae & Clusters ═══
    {"name": "Ring Nebula", "catalog_id": "M57", "alt_catalog_ids": "NGC 6720",
     "target_type": "Planetary Nebula", "ra_hours": 18.893, "dec_degrees": 33.03,
     "magnitude": 8.8, "size_arcmin": 1.5, "size_arcmin_minor": 1.0,
     "constellation": "Lyra", "season": "Summer", "difficulty": "Easy",
     "recommended_min_hours": 4, "narrowband_target": True, "broadband_target": True,
     "description": "Classic planetary nebula ring shape."},
    {"name": "Dumbbell Nebula", "catalog_id": "M27", "alt_catalog_ids": "NGC 6853",
     "target_type": "Planetary Nebula", "ra_hours": 19.993, "dec_degrees": 22.72,
     "magnitude": 7.5, "size_arcmin": 8, "size_arcmin_minor": 6,
     "constellation": "Vulpecula", "season": "Summer", "difficulty": "Easy",
     "recommended_min_hours": 3, "narrowband_target": True, "broadband_target": True,
     "description": "Bright, large planetary nebula."},
    {"name": "Owl Nebula", "catalog_id": "M97", "alt_catalog_ids": "NGC 3587",
     "target_type": "Planetary Nebula", "ra_hours": 11.248, "dec_degrees": 55.02,
     "magnitude": 9.9, "size_arcmin": 3.4, "size_arcmin_minor": 3.3,
     "constellation": "Ursa Major", "season": "Spring", "difficulty": "Moderate",
     "recommended_min_hours": 6, "narrowband_target": True, "broadband_target": True,
     "description": "Round planetary nebula with dark eyes. Near M108 galaxy."},
    {"name": "Hercules Cluster", "catalog_id": "M13", "alt_catalog_ids": "NGC 6205",
     "target_type": "Globular Cluster", "ra_hours": 16.695, "dec_degrees": 36.46,
     "magnitude": 5.8, "size_arcmin": 20, "size_arcmin_minor": 20,
     "constellation": "Hercules", "season": "Summer", "difficulty": "Easy",
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": "King of globular clusters in the north."},

    # ═══ AUTUMN ═══
    {"name": "Wizard Nebula", "catalog_id": "NGC 7380", "alt_catalog_ids": "Sh2-142",
     "target_type": "Emission Nebula", "ra_hours": 22.787, "dec_degrees": 58.13,
     "magnitude": 7.2, "size_arcmin": 25, "size_arcmin_minor": 25,
     "constellation": "Cepheus", "season": "Autumn", "difficulty": "Moderate",
     "recommended_min_hours": 8, "narrowband_target": True, "broadband_target": False,
     "description": "Emission nebula with wizard-like dust pillars."},
    {"name": "Iris Nebula", "catalog_id": "NGC 7023", "alt_catalog_ids": "Caldwell 4",
     "target_type": "Reflection Nebula", "ra_hours": 21.019, "dec_degrees": 68.17,
     "magnitude": 6.8, "size_arcmin": 18, "size_arcmin_minor": 18,
     "constellation": "Cepheus", "season": "Autumn", "difficulty": "Moderate",
     "recommended_min_hours": 6, "narrowband_target": False, "broadband_target": True,
     "description": "Beautiful blue/purple reflection nebula with surrounding dust."},
    {"name": "Helix Nebula", "catalog_id": "NGC 7293", "alt_catalog_ids": "Caldwell 63",
     "target_type": "Planetary Nebula", "ra_hours": 22.493, "dec_degrees": -20.84,
     "magnitude": 7.3, "size_arcmin": 25, "size_arcmin_minor": 20,
     "constellation": "Aquarius", "season": "Autumn", "difficulty": "Moderate",
     "recommended_min_hours": 6, "narrowband_target": True, "broadband_target": True,
     "description": "Closest planetary nebula. Low from 40N."},
    {"name": "NGC 7331 & Stephan's Quintet", "catalog_id": "NGC 7331", "alt_catalog_ids": "Caldwell 30",
     "target_type": "Galaxy Group", "ra_hours": 22.617, "dec_degrees": 34.42,
     "magnitude": 9.5, "size_arcmin": 10, "size_arcmin_minor": 4,
     "constellation": "Pegasus", "season": "Autumn", "difficulty": "Moderate",
     "recommended_min_hours": 6, "narrowband_target": False, "broadband_target": True,
     "description": "Bright spiral with nearby Stephan's Quintet compact group."},
    {"name": "Fireworks Galaxy", "catalog_id": "NGC 6946", "alt_catalog_ids": "Caldwell 12",
     "target_type": "Spiral Galaxy", "ra_hours": 20.580, "dec_degrees": 60.15,
     "magnitude": 9.6, "size_arcmin": 11, "size_arcmin_minor": 10,
     "constellation": "Cepheus", "season": "Autumn", "difficulty": "Moderate",
     "recommended_min_hours": 6, "narrowband_target": True, "broadband_target": True,
     "description": "Face-on spiral with many recorded supernovae."},

    # ═══ Wide-field ═══
    {"name": "Milky Way Core", "catalog_id": "Sgr MW Core", "alt_catalog_ids": "",
     "target_type": "Star Field", "ra_hours": 17.761, "dec_degrees": -29.01,
     "magnitude": None, "size_arcmin": 600, "size_arcmin_minor": 300,
     "constellation": "Sagittarius", "season": "Summer", "difficulty": "Easy",
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": "Galactic center region. Very low from 40N but stunning when visible."},
    {"name": "Cygnus Star Cloud", "catalog_id": "IC 1318 Region", "alt_catalog_ids": "",
     "target_type": "Star Field", "ra_hours": 20.333, "dec_degrees": 40.00,
     "magnitude": None, "size_arcmin": 300, "size_arcmin_minor": 200,
     "constellation": "Cygnus", "season": "Summer", "difficulty": "Easy",
     "recommended_min_hours": 2, "narrowband_target": True, "broadband_target": True,
     "description": "Rich Milky Way star field with extensive emission nebulosity."},

    # ═══ SOLAR SYSTEM ═══
    {"name": "The Sun", "catalog_id": "Sun", "alt_catalog_ids": "Sol",
     "target_type": "Sun", "ra_hours": 0, "dec_degrees": 0,
     "magnitude": -26.7, "size_arcmin": 32, "size_arcmin_minor": 32,
     "constellation": None, "season": None, "difficulty": "Moderate",
     "recommended_min_hours": 0, "narrowband_target": True, "broadband_target": True,
     "description": "⚠️ SAFETY WARNING: Never point a telescope at the Sun without a proper solar filter. Unfiltered sunlight will cause instant, permanent eye damage and destroy equipment. Use dedicated white-light or Hα solar filters only."},
    {"name": "The Moon", "catalog_id": "Moon", "alt_catalog_ids": "Luna",
     "target_type": "Moon", "ra_hours": 0, "dec_degrees": 0,
     "magnitude": -12.7, "size_arcmin": 31, "size_arcmin_minor": 31,
     "constellation": None, "season": None, "difficulty": "Easy",
     "recommended_min_hours": 0, "narrowband_target": False, "broadband_target": True,
     "description": "Earth's natural satellite. Great for high-resolution imaging and mosaics."},
    {"name": "Mercury", "catalog_id": "Mercury", "alt_catalog_ids": "",
     "target_type": "Planet", "ra_hours": 0, "dec_degrees": 0,
     "magnitude": -1.9, "size_arcmin": 0.18, "size_arcmin_minor": 0.18,
     "constellation": None, "season": None, "difficulty": "Hard",
     "recommended_min_hours": 0, "narrowband_target": False, "broadband_target": True,
     "description": "Innermost planet. Challenging due to proximity to the Sun. Best imaged at greatest elongation."},
    {"name": "Venus", "catalog_id": "Venus", "alt_catalog_ids": "",
     "target_type": "Planet", "ra_hours": 0, "dec_degrees": 0,
     "magnitude": -4.6, "size_arcmin": 1.0, "size_arcmin_minor": 1.0,
     "constellation": None, "season": None, "difficulty": "Moderate",
     "recommended_min_hours": 0, "narrowband_target": False, "broadband_target": True,
     "description": "Shows phases like the Moon. UV imaging reveals cloud detail."},
    {"name": "Mars", "catalog_id": "Mars", "alt_catalog_ids": "",
     "target_type": "Planet", "ra_hours": 0, "dec_degrees": 0,
     "magnitude": -2.9, "size_arcmin": 0.42, "size_arcmin_minor": 0.42,
     "constellation": None, "season": None, "difficulty": "Moderate",
     "recommended_min_hours": 0, "narrowband_target": False, "broadband_target": True,
     "description": "Best imaged near opposition when closest to Earth. Shows polar caps and surface features."},
    {"name": "Jupiter", "catalog_id": "Jupiter", "alt_catalog_ids": "",
     "target_type": "Planet", "ra_hours": 0, "dec_degrees": 0,
     "magnitude": -2.7, "size_arcmin": 0.83, "size_arcmin_minor": 0.73,
     "constellation": None, "season": None, "difficulty": "Easy",
     "recommended_min_hours": 0, "narrowband_target": False, "broadband_target": True,
     "description": "Largest planet. Cloud bands, Great Red Spot, and Galilean moons visible."},
    {"name": "Saturn", "catalog_id": "Saturn", "alt_catalog_ids": "",
     "target_type": "Planet", "ra_hours": 0, "dec_degrees": 0,
     "magnitude": 0.7, "size_arcmin": 0.70, "size_arcmin_minor": 0.30,
     "constellation": None, "season": None, "difficulty": "Easy",
     "recommended_min_hours": 0, "narrowband_target": False, "broadband_target": True,
     "description": "The ringed planet. Ring system and Cassini Division visible in good seeing."},
    {"name": "Uranus", "catalog_id": "Uranus", "alt_catalog_ids": "",
     "target_type": "Planet", "ra_hours": 0, "dec_degrees": 0,
     "magnitude": 5.7, "size_arcmin": 0.06, "size_arcmin_minor": 0.06,
     "constellation": None, "season": None, "difficulty": "Hard",
     "recommended_min_hours": 0, "narrowband_target": False, "broadband_target": True,
     "description": "Ice giant. Appears as a small blue-green disc. Moons visible with large apertures."},
    {"name": "Neptune", "catalog_id": "Neptune", "alt_catalog_ids": "",
     "target_type": "Planet", "ra_hours": 0, "dec_degrees": 0,
     "magnitude": 7.8, "size_arcmin": 0.04, "size_arcmin_minor": 0.04,
     "constellation": None, "season": None, "difficulty": "Hard",
     "recommended_min_hours": 0, "narrowband_target": False, "broadband_target": True,
     "description": "Outermost planet. Tiny blue disc. Triton visible with long exposures."},
]
