"""Expanded catalog — Messier + Caldwell + popular astrophotography targets.
Merged with DSO_CATALOG at startup via catalog_id deduplication."""

EXPANDED_CATALOG = [
    {"name": 'Star Cluster', "catalog_id": 'M2', "alt_catalog_ids": 'NGC 7089',
     "target_type": 'Globular Cluster', "ra_hours": 21.5575, "dec_degrees": -0.82,
     "magnitude": 6.3, "size_arcmin": 13, "size_arcmin_minor": 13,
     "constellation": 'Aquarius', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Rich compressed globular cluster requiring moderate aperture to resolve.'},
    {"name": 'Star Cluster', "catalog_id": 'M3', "alt_catalog_ids": 'NGC 5272',
     "target_type": 'Globular Cluster', "ra_hours": 13.7031, "dec_degrees": 28.38,
     "magnitude": 6.2, "size_arcmin": 16, "size_arcmin_minor": 16,
     "constellation": 'Canes Venatici', "season": 'Spring', "difficulty": 'Easy',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'One of the finest globulars. Over 500,000 stars in a tight sphere.'},
    {"name": 'Star Cluster', "catalog_id": 'M4', "alt_catalog_ids": 'NGC 6121',
     "target_type": 'Globular Cluster', "ra_hours": 16.3931, "dec_degrees": -26.53,
     "magnitude": 5.6, "size_arcmin": 26, "size_arcmin_minor": 26,
     "constellation": 'Scorpius', "season": 'Summer', "difficulty": 'Easy',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Nearest bright globular. Easily resolved with small telescopes.'},
    {"name": 'Star Cluster', "catalog_id": 'M5', "alt_catalog_ids": 'NGC 5904',
     "target_type": 'Globular Cluster', "ra_hours": 15.3094, "dec_degrees": 2.08,
     "magnitude": 5.7, "size_arcmin": 17, "size_arcmin_minor": 17,
     "constellation": 'Serpens', "season": 'Summer', "difficulty": 'Easy',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Superb globular rivaling M13 in beauty. Rich and well-resolved.'},
    {"name": 'Butterfly Cluster', "catalog_id": 'M6', "alt_catalog_ids": 'NGC 6405',
     "target_type": 'Open Cluster', "ra_hours": 17.6683, "dec_degrees": -32.22,
     "magnitude": 4.2, "size_arcmin": 15, "size_arcmin_minor": 15,
     "constellation": 'Scorpius', "season": 'Summer', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Bright open cluster with butterfly-shaped star pattern.'},
    {"name": 'Ptolemy Cluster', "catalog_id": 'M7', "alt_catalog_ids": 'NGC 6475',
     "target_type": 'Open Cluster', "ra_hours": 17.8975, "dec_degrees": -34.82,
     "magnitude": 3.3, "size_arcmin": 80, "size_arcmin_minor": 80,
     "constellation": 'Scorpius', "season": 'Summer', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Large bright naked-eye open cluster in the southern sky.'},
    {"name": 'Star Cluster', "catalog_id": 'M9', "alt_catalog_ids": 'NGC 6333',
     "target_type": 'Globular Cluster', "ra_hours": 17.32, "dec_degrees": -18.52,
     "magnitude": 7.7, "size_arcmin": 9, "size_arcmin_minor": 9,
     "constellation": 'Ophiuchus', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Compact globular near the galactic center.'},
    {"name": 'Star Cluster', "catalog_id": 'M10', "alt_catalog_ids": 'NGC 6254',
     "target_type": 'Globular Cluster', "ra_hours": 16.9525, "dec_degrees": -4.1,
     "magnitude": 6.6, "size_arcmin": 15, "size_arcmin_minor": 15,
     "constellation": 'Ophiuchus', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Bright globular cluster. Pair with M12 just 3 degrees away.'},
    {"name": 'Wild Duck Cluster', "catalog_id": 'M11', "alt_catalog_ids": 'NGC 6705',
     "target_type": 'Open Cluster', "ra_hours": 18.8517, "dec_degrees": -6.27,
     "magnitude": 5.8, "size_arcmin": 14, "size_arcmin_minor": 14,
     "constellation": 'Scutum', "season": 'Summer', "difficulty": 'Easy',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'One of the richest and most compact open clusters known.'},
    {"name": 'Star Cluster', "catalog_id": 'M12', "alt_catalog_ids": 'NGC 6218',
     "target_type": 'Globular Cluster', "ra_hours": 16.7872, "dec_degrees": -1.95,
     "magnitude": 6.7, "size_arcmin": 15, "size_arcmin_minor": 15,
     "constellation": 'Ophiuchus', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Loose globular cluster. Pair with M10 just 3 degrees away.'},
    {"name": 'Star Cluster', "catalog_id": 'M14', "alt_catalog_ids": 'NGC 6402',
     "target_type": 'Globular Cluster', "ra_hours": 17.6267, "dec_degrees": -3.25,
     "magnitude": 7.6, "size_arcmin": 12, "size_arcmin_minor": 12,
     "constellation": 'Ophiuchus', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Moderately bright globular containing over 150,000 stars.'},
    {"name": 'Great Pegasus Cluster', "catalog_id": 'M15', "alt_catalog_ids": 'NGC 7078',
     "target_type": 'Globular Cluster', "ra_hours": 21.4994, "dec_degrees": 12.17,
     "magnitude": 6.2, "size_arcmin": 12, "size_arcmin_minor": 12,
     "constellation": 'Pegasus', "season": 'Summer', "difficulty": 'Easy',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Dense globular with extremely compact core. Contains planetary nebula Pease 1.'},
    {"name": 'Star Cluster', "catalog_id": 'M18', "alt_catalog_ids": 'NGC 6613',
     "target_type": 'Open Cluster', "ra_hours": 18.3317, "dec_degrees": -17.08,
     "magnitude": 6.9, "size_arcmin": 9, "size_arcmin_minor": 9,
     "constellation": 'Sagittarius', "season": 'Summer', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Small open cluster between M17 and M24.'},
    {"name": 'Star Cluster', "catalog_id": 'M19', "alt_catalog_ids": 'NGC 6273',
     "target_type": 'Globular Cluster', "ra_hours": 17.0439, "dec_degrees": -26.27,
     "magnitude": 6.8, "size_arcmin": 14, "size_arcmin_minor": 14,
     "constellation": 'Ophiuchus', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Oblate globular — one of the most elongated Messier globulars.'},
    {"name": 'Star Cluster', "catalog_id": 'M21', "alt_catalog_ids": 'NGC 6531',
     "target_type": 'Open Cluster', "ra_hours": 18.0767, "dec_degrees": -22.5,
     "magnitude": 5.9, "size_arcmin": 13, "size_arcmin_minor": 13,
     "constellation": 'Sagittarius', "season": 'Summer', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Compact open cluster adjacent to the Trifid Nebula (M20).'},
    {"name": 'Sagittarius Cluster', "catalog_id": 'M22', "alt_catalog_ids": 'NGC 6656',
     "target_type": 'Globular Cluster', "ra_hours": 18.6067, "dec_degrees": -23.9,
     "magnitude": 5.1, "size_arcmin": 24, "size_arcmin_minor": 24,
     "constellation": 'Sagittarius', "season": 'Summer', "difficulty": 'Easy',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'One of the brightest and nearest globular clusters.'},
    {"name": 'Star Cluster', "catalog_id": 'M23', "alt_catalog_ids": 'NGC 6494',
     "target_type": 'Open Cluster', "ra_hours": 17.9467, "dec_degrees": -19.02,
     "magnitude": 5.5, "size_arcmin": 27, "size_arcmin_minor": 27,
     "constellation": 'Sagittarius', "season": 'Summer', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Rich open cluster with about 150 stars.'},
    {"name": 'Sagittarius Star Cloud', "catalog_id": 'M24', "alt_catalog_ids": 'IC 4715',
     "target_type": 'Star Field', "ra_hours": 18.2817, "dec_degrees": -18.5,
     "magnitude": 4.6, "size_arcmin": 90, "size_arcmin_minor": 60,
     "constellation": 'Sagittarius', "season": 'Summer', "difficulty": 'Easy',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Densest visible concentration of Milky Way stars.'},
    {"name": 'Star Cluster', "catalog_id": 'M25', "alt_catalog_ids": 'IC 4725',
     "target_type": 'Open Cluster', "ra_hours": 18.5267, "dec_degrees": -19.25,
     "magnitude": 4.6, "size_arcmin": 32, "size_arcmin_minor": 32,
     "constellation": 'Sagittarius', "season": 'Summer', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Large bright open cluster containing the Cepheid U Sagittarii.'},
    {"name": 'Star Cluster', "catalog_id": 'M26', "alt_catalog_ids": 'NGC 6694',
     "target_type": 'Open Cluster', "ra_hours": 18.7533, "dec_degrees": -9.4,
     "magnitude": 8.0, "size_arcmin": 15, "size_arcmin_minor": 15,
     "constellation": 'Scutum', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Compact open cluster with a notable dark lane through its center.'},
    {"name": 'Star Cluster', "catalog_id": 'M28', "alt_catalog_ids": 'NGC 6626',
     "target_type": 'Globular Cluster', "ra_hours": 18.4092, "dec_degrees": -24.87,
     "magnitude": 6.8, "size_arcmin": 11, "size_arcmin_minor": 11,
     "constellation": 'Sagittarius', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Compact globular near M22. Contains a millisecond pulsar.'},
    {"name": 'Star Cluster', "catalog_id": 'M29', "alt_catalog_ids": 'NGC 6913',
     "target_type": 'Open Cluster', "ra_hours": 20.3983, "dec_degrees": 38.53,
     "magnitude": 6.6, "size_arcmin": 7, "size_arcmin_minor": 7,
     "constellation": 'Cygnus', "season": 'Summer', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Small open cluster in a rich Cygnus Milky Way field.'},
    {"name": 'Star Cluster', "catalog_id": 'M30', "alt_catalog_ids": 'NGC 7099',
     "target_type": 'Globular Cluster', "ra_hours": 21.6728, "dec_degrees": -23.18,
     "magnitude": 7.2, "size_arcmin": 11, "size_arcmin_minor": 11,
     "constellation": 'Capricornus', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Core-collapsed globular. Often the hardest Messier marathon target.'},
    {"name": 'Andromeda Satellite', "catalog_id": 'M32', "alt_catalog_ids": 'NGC 221',
     "target_type": 'Elliptical Galaxy', "ra_hours": 0.7117, "dec_degrees": 40.87,
     "magnitude": 8.1, "size_arcmin": 8, "size_arcmin_minor": 6,
     "constellation": 'Andromeda', "season": 'Autumn', "difficulty": 'Easy',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Compact elliptical companion of M31.'},
    {"name": 'Star Cluster', "catalog_id": 'M34', "alt_catalog_ids": 'NGC 1039',
     "target_type": 'Open Cluster', "ra_hours": 2.7, "dec_degrees": 42.78,
     "magnitude": 5.2, "size_arcmin": 35, "size_arcmin_minor": 35,
     "constellation": 'Perseus', "season": 'Winter', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Large open cluster visible to the naked eye.'},
    {"name": 'Star Cluster', "catalog_id": 'M35', "alt_catalog_ids": 'NGC 2168',
     "target_type": 'Open Cluster', "ra_hours": 6.1483, "dec_degrees": 24.33,
     "magnitude": 5.1, "size_arcmin": 28, "size_arcmin_minor": 28,
     "constellation": 'Gemini', "season": 'Winter', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Rich bright open cluster. NGC 2158 lies nearby for a great pair.'},
    {"name": 'Pinwheel Cluster', "catalog_id": 'M36', "alt_catalog_ids": 'NGC 1960',
     "target_type": 'Open Cluster', "ra_hours": 5.6017, "dec_degrees": 34.13,
     "magnitude": 6.0, "size_arcmin": 12, "size_arcmin_minor": 12,
     "constellation": 'Auriga', "season": 'Winter', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'One of three bright Auriga clusters with M37 and M38.'},
    {"name": 'Salt-and-Pepper Cluster', "catalog_id": 'M37', "alt_catalog_ids": 'NGC 2099',
     "target_type": 'Open Cluster', "ra_hours": 5.8733, "dec_degrees": 32.55,
     "magnitude": 5.6, "size_arcmin": 24, "size_arcmin_minor": 24,
     "constellation": 'Auriga', "season": 'Winter', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Richest of the three Auriga clusters. Over 500 members.'},
    {"name": 'Starfish Cluster', "catalog_id": 'M38', "alt_catalog_ids": 'NGC 1912',
     "target_type": 'Open Cluster', "ra_hours": 5.4733, "dec_degrees": 35.83,
     "magnitude": 6.4, "size_arcmin": 21, "size_arcmin_minor": 21,
     "constellation": 'Auriga', "season": 'Winter', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Open cluster with cruciform pattern.'},
    {"name": 'Star Cluster', "catalog_id": 'M39', "alt_catalog_ids": 'NGC 7092',
     "target_type": 'Open Cluster', "ra_hours": 21.53, "dec_degrees": 48.43,
     "magnitude": 4.6, "size_arcmin": 32, "size_arcmin_minor": 32,
     "constellation": 'Cygnus', "season": 'Summer', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Large loose nearby open cluster.'},
    {"name": 'Winnecke 4', "catalog_id": 'M40', "alt_catalog_ids": 'WNC 4',
     "target_type": 'Star Field', "ra_hours": 12.3703, "dec_degrees": 58.08,
     "magnitude": 8.4, "size_arcmin": 1, "size_arcmin_minor": 1,
     "constellation": 'Ursa Major', "season": 'Spring', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Visual double star. The least impressive Messier object.'},
    {"name": 'Little Beehive', "catalog_id": 'M41', "alt_catalog_ids": 'NGC 2287',
     "target_type": 'Open Cluster', "ra_hours": 6.7667, "dec_degrees": -20.73,
     "magnitude": 4.5, "size_arcmin": 38, "size_arcmin_minor": 38,
     "constellation": 'Canis Major', "season": 'Winter', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Bright open cluster 4 degrees south of Sirius.'},
    {"name": "De Mairan's Nebula", "catalog_id": 'M43', "alt_catalog_ids": 'NGC 1982',
     "target_type": 'Emission Nebula', "ra_hours": 5.5933, "dec_degrees": -5.27,
     "magnitude": 9.0, "size_arcmin": 20, "size_arcmin_minor": 15,
     "constellation": 'Orion', "season": 'Winter', "difficulty": 'Easy',
     "recommended_min_hours": 3, "narrowband_target": True, "broadband_target": True,
     "description": 'Detached portion of the Orion Nebula.'},
    {"name": 'Beehive Cluster', "catalog_id": 'M44', "alt_catalog_ids": 'NGC 2632',
     "target_type": 'Open Cluster', "ra_hours": 8.6683, "dec_degrees": 19.67,
     "magnitude": 3.1, "size_arcmin": 95, "size_arcmin_minor": 95,
     "constellation": 'Cancer', "season": 'Spring', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Large naked-eye open cluster. One of the nearest to Earth.'},
    {"name": 'Star Cluster', "catalog_id": 'M46', "alt_catalog_ids": 'NGC 2437',
     "target_type": 'Open Cluster', "ra_hours": 7.6967, "dec_degrees": -14.82,
     "magnitude": 6.1, "size_arcmin": 27, "size_arcmin_minor": 27,
     "constellation": 'Puppis', "season": 'Winter', "difficulty": 'Easy',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Rich cluster containing the planetary nebula NGC 2438.'},
    {"name": 'Star Cluster', "catalog_id": 'M47', "alt_catalog_ids": 'NGC 2422',
     "target_type": 'Open Cluster', "ra_hours": 7.61, "dec_degrees": -14.5,
     "magnitude": 4.4, "size_arcmin": 30, "size_arcmin_minor": 30,
     "constellation": 'Puppis', "season": 'Winter', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Bright coarse cluster 1.5 degrees west of M46.'},
    {"name": 'Star Cluster', "catalog_id": 'M48', "alt_catalog_ids": 'NGC 2548',
     "target_type": 'Open Cluster', "ra_hours": 8.23, "dec_degrees": -5.8,
     "magnitude": 5.8, "size_arcmin": 54, "size_arcmin_minor": 54,
     "constellation": 'Hydra', "season": 'Spring', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Large loose open cluster.'},
    {"name": 'Elliptical Galaxy', "catalog_id": 'M49', "alt_catalog_ids": 'NGC 4472',
     "target_type": 'Elliptical Galaxy', "ra_hours": 12.4964, "dec_degrees": 8.0,
     "magnitude": 8.4, "size_arcmin": 9, "size_arcmin_minor": 7,
     "constellation": 'Virgo', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Brightest galaxy in the Virgo Cluster.'},
    {"name": 'Star Cluster', "catalog_id": 'M50', "alt_catalog_ids": 'NGC 2323',
     "target_type": 'Open Cluster', "ra_hours": 7.0533, "dec_degrees": -8.33,
     "magnitude": 5.9, "size_arcmin": 16, "size_arcmin_minor": 16,
     "constellation": 'Monoceros', "season": 'Winter', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Compact open cluster between Sirius and Procyon.'},
    {"name": 'Star Cluster', "catalog_id": 'M52', "alt_catalog_ids": 'NGC 7654',
     "target_type": 'Open Cluster', "ra_hours": 23.4033, "dec_degrees": 61.58,
     "magnitude": 6.9, "size_arcmin": 13, "size_arcmin_minor": 13,
     "constellation": 'Cassiopeia', "season": 'Autumn', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Rich open cluster near the Bubble Nebula.'},
    {"name": 'Star Cluster', "catalog_id": 'M53', "alt_catalog_ids": 'NGC 5024',
     "target_type": 'Globular Cluster', "ra_hours": 13.2153, "dec_degrees": 18.17,
     "magnitude": 7.6, "size_arcmin": 13, "size_arcmin_minor": 13,
     "constellation": 'Coma Berenices', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Distant compact globular cluster at 58,000 light-years.'},
    {"name": 'Star Cluster', "catalog_id": 'M54', "alt_catalog_ids": 'NGC 6715',
     "target_type": 'Globular Cluster', "ra_hours": 18.9175, "dec_degrees": -30.48,
     "magnitude": 7.6, "size_arcmin": 9, "size_arcmin_minor": 9,
     "constellation": 'Sagittarius', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Globular belonging to the Sagittarius Dwarf Galaxy.'},
    {"name": 'Star Cluster', "catalog_id": 'M55', "alt_catalog_ids": 'NGC 6809',
     "target_type": 'Globular Cluster', "ra_hours": 19.6667, "dec_degrees": -30.97,
     "magnitude": 6.3, "size_arcmin": 19, "size_arcmin_minor": 19,
     "constellation": 'Sagittarius', "season": 'Summer', "difficulty": 'Easy',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Large loose globular. Well-resolved with modest aperture.'},
    {"name": 'Star Cluster', "catalog_id": 'M56', "alt_catalog_ids": 'NGC 6779',
     "target_type": 'Globular Cluster', "ra_hours": 19.2767, "dec_degrees": 30.18,
     "magnitude": 8.3, "size_arcmin": 7, "size_arcmin_minor": 7,
     "constellation": 'Lyra', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Compact globular between Albireo and M57.'},
    {"name": 'Barred Spiral', "catalog_id": 'M58', "alt_catalog_ids": 'NGC 4579',
     "target_type": 'Spiral Galaxy', "ra_hours": 12.6286, "dec_degrees": 11.82,
     "magnitude": 9.7, "size_arcmin": 6, "size_arcmin_minor": 5,
     "constellation": 'Virgo', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Barred spiral in the Virgo Cluster.'},
    {"name": 'Elliptical Galaxy', "catalog_id": 'M59', "alt_catalog_ids": 'NGC 4621',
     "target_type": 'Elliptical Galaxy', "ra_hours": 12.7006, "dec_degrees": 11.65,
     "magnitude": 9.6, "size_arcmin": 5, "size_arcmin_minor": 3,
     "constellation": 'Virgo', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Elliptical in the Virgo Cluster. Pair with M60.'},
    {"name": 'Elliptical Galaxy', "catalog_id": 'M60', "alt_catalog_ids": 'NGC 4649',
     "target_type": 'Elliptical Galaxy', "ra_hours": 12.7278, "dec_degrees": 11.55,
     "magnitude": 8.8, "size_arcmin": 7, "size_arcmin_minor": 6,
     "constellation": 'Virgo', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Third largest Virgo Cluster galaxy.'},
    {"name": 'Face-on Spiral', "catalog_id": 'M61', "alt_catalog_ids": 'NGC 4303',
     "target_type": 'Spiral Galaxy', "ra_hours": 12.3653, "dec_degrees": 4.47,
     "magnitude": 9.7, "size_arcmin": 6, "size_arcmin_minor": 5,
     "constellation": 'Virgo', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Face-on barred spiral with many observed supernovae.'},
    {"name": 'Flickering Globular', "catalog_id": 'M62', "alt_catalog_ids": 'NGC 6266',
     "target_type": 'Globular Cluster', "ra_hours": 17.0203, "dec_degrees": -30.12,
     "magnitude": 6.5, "size_arcmin": 14, "size_arcmin_minor": 14,
     "constellation": 'Ophiuchus', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Asymmetric globular near the galactic center.'},
    {"name": 'King Cobra Cluster', "catalog_id": 'M67', "alt_catalog_ids": 'NGC 2682',
     "target_type": 'Open Cluster', "ra_hours": 8.8567, "dec_degrees": 11.82,
     "magnitude": 6.9, "size_arcmin": 30, "size_arcmin_minor": 30,
     "constellation": 'Cancer', "season": 'Spring', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'One of the oldest known open clusters at about 4 billion years.'},
    {"name": 'Star Cluster', "catalog_id": 'M68', "alt_catalog_ids": 'NGC 4590',
     "target_type": 'Globular Cluster', "ra_hours": 12.6578, "dec_degrees": -26.75,
     "magnitude": 7.8, "size_arcmin": 12, "size_arcmin_minor": 12,
     "constellation": 'Hydra', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Loose globular in Hydra.'},
    {"name": 'Star Cluster', "catalog_id": 'M69', "alt_catalog_ids": 'NGC 6637',
     "target_type": 'Globular Cluster', "ra_hours": 18.5231, "dec_degrees": -32.35,
     "magnitude": 7.6, "size_arcmin": 7, "size_arcmin_minor": 7,
     "constellation": 'Sagittarius', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Small concentrated globular in the Sagittarius star cloud.'},
    {"name": 'Star Cluster', "catalog_id": 'M70', "alt_catalog_ids": 'NGC 6681',
     "target_type": 'Globular Cluster', "ra_hours": 18.7203, "dec_degrees": -32.3,
     "magnitude": 7.9, "size_arcmin": 8, "size_arcmin_minor": 8,
     "constellation": 'Sagittarius', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Compact core-collapsed globular.'},
    {"name": 'Star Cluster', "catalog_id": 'M71', "alt_catalog_ids": 'NGC 6838',
     "target_type": 'Globular Cluster', "ra_hours": 19.8961, "dec_degrees": 18.78,
     "magnitude": 8.2, "size_arcmin": 7, "size_arcmin_minor": 7,
     "constellation": 'Sagitta', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Loose globular sometimes mistaken for an open cluster.'},
    {"name": 'Star Cluster', "catalog_id": 'M72', "alt_catalog_ids": 'NGC 6981',
     "target_type": 'Globular Cluster', "ra_hours": 20.8911, "dec_degrees": -12.53,
     "magnitude": 9.3, "size_arcmin": 6, "size_arcmin_minor": 6,
     "constellation": 'Aquarius', "season": 'Summer', "difficulty": 'Hard',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Faint distant globular. One of the more challenging Messier objects.'},
    {"name": 'Asterism', "catalog_id": 'M73', "alt_catalog_ids": 'NGC 6994',
     "target_type": 'Star Field', "ra_hours": 20.9817, "dec_degrees": -12.63,
     "magnitude": 9.0, "size_arcmin": 3, "size_arcmin_minor": 3,
     "constellation": 'Aquarius', "season": 'Summer', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Group of 4 stars — an asterism, not a true cluster.'},
    {"name": 'Phantom Galaxy', "catalog_id": 'M74', "alt_catalog_ids": 'NGC 628',
     "target_type": 'Spiral Galaxy', "ra_hours": 1.6117, "dec_degrees": 15.78,
     "magnitude": 9.4, "size_arcmin": 10, "size_arcmin_minor": 10,
     "constellation": 'Pisces', "season": 'Autumn', "difficulty": 'Hard',
     "recommended_min_hours": 4, "narrowband_target": False, "broadband_target": True,
     "description": 'Grand design face-on spiral. Low surface brightness.'},
    {"name": 'Star Cluster', "catalog_id": 'M75', "alt_catalog_ids": 'NGC 6864',
     "target_type": 'Globular Cluster', "ra_hours": 20.1014, "dec_degrees": -21.92,
     "magnitude": 8.5, "size_arcmin": 6, "size_arcmin_minor": 6,
     "constellation": 'Sagittarius', "season": 'Summer', "difficulty": 'Hard',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Compact concentrated globular with very dense core.'},
    {"name": 'Little Dumbbell Nebula', "catalog_id": 'M76', "alt_catalog_ids": 'NGC 650',
     "target_type": 'Planetary Nebula', "ra_hours": 1.7067, "dec_degrees": 51.57,
     "magnitude": 10.1, "size_arcmin": 3, "size_arcmin_minor": 2,
     "constellation": 'Perseus', "season": 'Autumn', "difficulty": 'Hard',
     "recommended_min_hours": 4, "narrowband_target": True, "broadband_target": False,
     "description": 'Faintest Messier object. Miniature version of M27.'},
    {"name": 'Cetus A', "catalog_id": 'M77', "alt_catalog_ids": 'NGC 1068',
     "target_type": 'Spiral Galaxy', "ra_hours": 2.7114, "dec_degrees": -0.01,
     "magnitude": 8.9, "size_arcmin": 7, "size_arcmin_minor": 6,
     "constellation": 'Cetus', "season": 'Winter', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Seyfert galaxy with active nucleus.'},
    {"name": 'Reflection Nebula', "catalog_id": 'M78', "alt_catalog_ids": 'NGC 2068',
     "target_type": 'Reflection Nebula', "ra_hours": 5.7783, "dec_degrees": 0.05,
     "magnitude": 8.3, "size_arcmin": 8, "size_arcmin_minor": 6,
     "constellation": 'Orion', "season": 'Winter', "difficulty": 'Moderate',
     "recommended_min_hours": 4, "narrowband_target": False, "broadband_target": True,
     "description": 'Brightest diffuse reflection nebula. Blue glow from young stars.'},
    {"name": 'Star Cluster', "catalog_id": 'M79', "alt_catalog_ids": 'NGC 1904',
     "target_type": 'Globular Cluster', "ra_hours": 5.4031, "dec_degrees": -24.52,
     "magnitude": 7.7, "size_arcmin": 9, "size_arcmin_minor": 9,
     "constellation": 'Lepus', "season": 'Winter', "difficulty": 'Moderate',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Winter globular — unusual for appearing opposite the galactic center.'},
    {"name": 'Star Cluster', "catalog_id": 'M80', "alt_catalog_ids": 'NGC 6093',
     "target_type": 'Globular Cluster', "ra_hours": 16.2842, "dec_degrees": -22.98,
     "magnitude": 7.3, "size_arcmin": 9, "size_arcmin_minor": 9,
     "constellation": 'Scorpius', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Dense globular midway between Antares and Graffias.'},
    {"name": 'Southern Pinwheel', "catalog_id": 'M83', "alt_catalog_ids": 'NGC 5236',
     "target_type": 'Spiral Galaxy', "ra_hours": 13.6169, "dec_degrees": -29.87,
     "magnitude": 7.5, "size_arcmin": 13, "size_arcmin_minor": 12,
     "constellation": 'Hydra', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 4, "narrowband_target": False, "broadband_target": True,
     "description": 'Magnificent barred spiral with active star formation.'},
    {"name": 'Elliptical Galaxy', "catalog_id": 'M85', "alt_catalog_ids": 'NGC 4382',
     "target_type": 'Elliptical Galaxy', "ra_hours": 12.4233, "dec_degrees": 18.19,
     "magnitude": 9.1, "size_arcmin": 7, "size_arcmin_minor": 5,
     "constellation": 'Coma Berenices', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Lenticular galaxy at the north edge of the Virgo Cluster.'},
    {"name": 'Virgo A', "catalog_id": 'M87', "alt_catalog_ids": 'NGC 4486',
     "target_type": 'Elliptical Galaxy', "ra_hours": 12.5136, "dec_degrees": 12.39,
     "magnitude": 8.6, "size_arcmin": 7, "size_arcmin_minor": 7,
     "constellation": 'Virgo', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Supergiant elliptical. Home of the first photographed black hole.'},
    {"name": 'Spiral Galaxy', "catalog_id": 'M88', "alt_catalog_ids": 'NGC 4501',
     "target_type": 'Spiral Galaxy', "ra_hours": 12.5333, "dec_degrees": 14.42,
     "magnitude": 9.6, "size_arcmin": 7, "size_arcmin_minor": 4,
     "constellation": 'Coma Berenices', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Multi-armed spiral in the Virgo Cluster.'},
    {"name": 'Elliptical Galaxy', "catalog_id": 'M89', "alt_catalog_ids": 'NGC 4552',
     "target_type": 'Elliptical Galaxy', "ra_hours": 12.5944, "dec_degrees": 12.55,
     "magnitude": 9.8, "size_arcmin": 4, "size_arcmin_minor": 4,
     "constellation": 'Virgo', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Nearly perfectly round elliptical in the Virgo Cluster.'},
    {"name": 'Spiral Galaxy', "catalog_id": 'M90', "alt_catalog_ids": 'NGC 4569',
     "target_type": 'Spiral Galaxy', "ra_hours": 12.6139, "dec_degrees": 13.16,
     "magnitude": 9.5, "size_arcmin": 10, "size_arcmin_minor": 5,
     "constellation": 'Virgo', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Large bright spiral. One of the few blueshifted galaxies.'},
    {"name": 'Barred Spiral', "catalog_id": 'M91', "alt_catalog_ids": 'NGC 4548',
     "target_type": 'Spiral Galaxy', "ra_hours": 12.5906, "dec_degrees": 14.5,
     "magnitude": 10.2, "size_arcmin": 5, "size_arcmin_minor": 4,
     "constellation": 'Coma Berenices', "season": 'Spring', "difficulty": 'Hard',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Barred spiral galaxy. One of the faintest Messier objects.'},
    {"name": 'Star Cluster', "catalog_id": 'M92', "alt_catalog_ids": 'NGC 6341',
     "target_type": 'Globular Cluster', "ra_hours": 17.2853, "dec_degrees": 43.14,
     "magnitude": 6.4, "size_arcmin": 11, "size_arcmin_minor": 11,
     "constellation": 'Hercules', "season": 'Summer', "difficulty": 'Easy',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Superb globular overshadowed by nearby M13.'},
    {"name": 'Star Cluster', "catalog_id": 'M93', "alt_catalog_ids": 'NGC 2447',
     "target_type": 'Open Cluster', "ra_hours": 7.7433, "dec_degrees": -23.87,
     "magnitude": 6.2, "size_arcmin": 22, "size_arcmin_minor": 22,
     "constellation": 'Puppis', "season": 'Winter', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Compact bright open cluster.'},
    {"name": "Croc's Eye Galaxy", "catalog_id": 'M94', "alt_catalog_ids": 'NGC 4736',
     "target_type": 'Spiral Galaxy', "ra_hours": 12.8481, "dec_degrees": 41.12,
     "magnitude": 8.2, "size_arcmin": 11, "size_arcmin_minor": 9,
     "constellation": 'Canes Venatici', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Bright ring galaxy with intense starburst ring.'},
    {"name": 'Barred Spiral', "catalog_id": 'M95', "alt_catalog_ids": 'NGC 3351',
     "target_type": 'Spiral Galaxy', "ra_hours": 10.7333, "dec_degrees": 11.7,
     "magnitude": 9.7, "size_arcmin": 7, "size_arcmin_minor": 5,
     "constellation": 'Leo', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Forms a trio with M96 and M105.'},
    {"name": 'Spiral Galaxy', "catalog_id": 'M96', "alt_catalog_ids": 'NGC 3368',
     "target_type": 'Spiral Galaxy', "ra_hours": 10.7794, "dec_degrees": 11.82,
     "magnitude": 9.2, "size_arcmin": 7, "size_arcmin_minor": 5,
     "constellation": 'Leo', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Brightest galaxy in the M96 Leo I group.'},
    {"name": 'Spiral Galaxy', "catalog_id": 'M98', "alt_catalog_ids": 'NGC 4192',
     "target_type": 'Spiral Galaxy', "ra_hours": 12.23, "dec_degrees": 14.9,
     "magnitude": 10.1, "size_arcmin": 10, "size_arcmin_minor": 3,
     "constellation": 'Coma Berenices', "season": 'Spring', "difficulty": 'Hard',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Edge-on spiral. Low surface brightness but elegant profile.'},
    {"name": 'Coma Pinwheel', "catalog_id": 'M99', "alt_catalog_ids": 'NGC 4254',
     "target_type": 'Spiral Galaxy', "ra_hours": 12.3139, "dec_degrees": 14.42,
     "magnitude": 9.9, "size_arcmin": 5, "size_arcmin_minor": 5,
     "constellation": 'Coma Berenices', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Grand design spiral with one notably longer arm.'},
    {"name": 'Mirror Galaxy', "catalog_id": 'M100', "alt_catalog_ids": 'NGC 4321',
     "target_type": 'Spiral Galaxy', "ra_hours": 12.3819, "dec_degrees": 15.82,
     "magnitude": 9.3, "size_arcmin": 7, "size_arcmin_minor": 6,
     "constellation": 'Coma Berenices', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Grand design face-on spiral. One of the brightest Virgo spirals.'},
    {"name": 'Spindle Galaxy', "catalog_id": 'M102', "alt_catalog_ids": 'NGC 5866',
     "target_type": 'Spiral Galaxy', "ra_hours": 15.1081, "dec_degrees": 55.76,
     "magnitude": 9.9, "size_arcmin": 5, "size_arcmin_minor": 2,
     "constellation": 'Draco', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Edge-on lenticular with a prominent dust lane.'},
    {"name": 'Star Cluster', "catalog_id": 'M103', "alt_catalog_ids": 'NGC 581',
     "target_type": 'Open Cluster', "ra_hours": 1.5533, "dec_degrees": 60.7,
     "magnitude": 7.4, "size_arcmin": 6, "size_arcmin_minor": 6,
     "constellation": 'Cassiopeia', "season": 'Autumn', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Open cluster near the W of Cassiopeia.'},
    {"name": 'Elliptical Galaxy', "catalog_id": 'M105', "alt_catalog_ids": 'NGC 3379',
     "target_type": 'Elliptical Galaxy', "ra_hours": 10.7972, "dec_degrees": 12.58,
     "magnitude": 9.3, "size_arcmin": 5, "size_arcmin_minor": 5,
     "constellation": 'Leo', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Elliptical in the Leo I group.'},
    {"name": 'Spiral Galaxy', "catalog_id": 'M106', "alt_catalog_ids": 'NGC 4258',
     "target_type": 'Spiral Galaxy', "ra_hours": 12.3161, "dec_degrees": 47.3,
     "magnitude": 8.4, "size_arcmin": 19, "size_arcmin_minor": 8,
     "constellation": 'Canes Venatici', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 4, "narrowband_target": True, "broadband_target": True,
     "description": 'Large bright spiral with anomalous arms visible in Halpha.'},
    {"name": 'Star Cluster', "catalog_id": 'M107', "alt_catalog_ids": 'NGC 6171',
     "target_type": 'Globular Cluster', "ra_hours": 16.5422, "dec_degrees": -13.05,
     "magnitude": 7.9, "size_arcmin": 10, "size_arcmin_minor": 10,
     "constellation": 'Ophiuchus', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Loose sparse globular. One of the less concentrated Messier globulars.'},
    {"name": 'Surfboard Galaxy', "catalog_id": 'M108', "alt_catalog_ids": 'NGC 3556',
     "target_type": 'Spiral Galaxy', "ra_hours": 11.1919, "dec_degrees": 55.67,
     "magnitude": 10.0, "size_arcmin": 8, "size_arcmin_minor": 2,
     "constellation": 'Ursa Major', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Edge-on spiral near M97. Often imaged together.'},
    {"name": 'Barred Spiral', "catalog_id": 'M109', "alt_catalog_ids": 'NGC 3992',
     "target_type": 'Spiral Galaxy', "ra_hours": 11.96, "dec_degrees": 53.37,
     "magnitude": 9.8, "size_arcmin": 8, "size_arcmin_minor": 5,
     "constellation": 'Ursa Major', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Largest Messier barred spiral near Phecda.'},
    {"name": 'Andromeda Satellite', "catalog_id": 'M110', "alt_catalog_ids": 'NGC 205',
     "target_type": 'Elliptical Galaxy', "ra_hours": 0.6728, "dec_degrees": 41.68,
     "magnitude": 8.5, "size_arcmin": 17, "size_arcmin_minor": 10,
     "constellation": 'Andromeda', "season": 'Autumn', "difficulty": 'Easy',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Second satellite of M31. Dwarf elliptical with unusual dust.'},
    {"name": 'Open Cluster', "catalog_id": 'C1', "alt_catalog_ids": 'NGC 188',
     "target_type": 'Open Cluster', "ra_hours": 0.74, "dec_degrees": 85.33,
     "magnitude": 8.1, "size_arcmin": 15, "size_arcmin_minor": 15,
     "constellation": 'Cepheus', "season": 'Autumn', "difficulty": 'Moderate',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'One of the oldest open clusters, near the North Celestial Pole.'},
    {"name": 'Bow Tie Nebula', "catalog_id": 'C2', "alt_catalog_ids": 'NGC 40',
     "target_type": 'Planetary Nebula', "ra_hours": 0.2169, "dec_degrees": 72.52,
     "magnitude": 11.6, "size_arcmin": 1, "size_arcmin_minor": 1,
     "constellation": 'Cepheus', "season": 'Autumn', "difficulty": 'Hard',
     "recommended_min_hours": 4, "narrowband_target": True, "broadband_target": False,
     "description": 'Small planetary nebula with bow-tie shape.'},
    {"name": 'Spiral Galaxy', "catalog_id": 'C3', "alt_catalog_ids": 'NGC 4236',
     "target_type": 'Spiral Galaxy', "ra_hours": 12.2783, "dec_degrees": 69.47,
     "magnitude": 9.7, "size_arcmin": 22, "size_arcmin_minor": 7,
     "constellation": 'Draco', "season": 'Spring', "difficulty": 'Hard',
     "recommended_min_hours": 4, "narrowband_target": False, "broadband_target": True,
     "description": 'Large but very low surface brightness barred spiral.'},
    {"name": 'Hidden Galaxy', "catalog_id": 'C5', "alt_catalog_ids": 'IC 342',
     "target_type": 'Spiral Galaxy', "ra_hours": 3.7803, "dec_degrees": 68.1,
     "magnitude": 9.2, "size_arcmin": 21, "size_arcmin_minor": 21,
     "constellation": 'Camelopardalis', "season": 'Winter', "difficulty": 'Hard',
     "recommended_min_hours": 5, "narrowband_target": False, "broadband_target": True,
     "description": 'One of the nearest large galaxies, heavily obscured by MW dust.'},
    {"name": "Cat's Eye Nebula", "catalog_id": 'C6', "alt_catalog_ids": 'NGC 6543',
     "target_type": 'Planetary Nebula', "ra_hours": 17.9758, "dec_degrees": 66.63,
     "magnitude": 8.1, "size_arcmin": 0.4, "size_arcmin_minor": 0.3,
     "constellation": 'Draco', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": True, "broadband_target": True,
     "description": 'One of the most structurally complex planetary nebulae known.'},
    {"name": 'Spiral Galaxy', "catalog_id": 'C7', "alt_catalog_ids": 'NGC 2403',
     "target_type": 'Spiral Galaxy', "ra_hours": 7.6144, "dec_degrees": 65.6,
     "magnitude": 8.9, "size_arcmin": 22, "size_arcmin_minor": 12,
     "constellation": 'Camelopardalis', "season": 'Winter', "difficulty": 'Moderate',
     "recommended_min_hours": 4, "narrowband_target": False, "broadband_target": True,
     "description": 'Bright spiral with prominent HII regions.'},
    {"name": 'Open Cluster', "catalog_id": 'C8', "alt_catalog_ids": 'NGC 559',
     "target_type": 'Open Cluster', "ra_hours": 1.4917, "dec_degrees": 63.3,
     "magnitude": 9.5, "size_arcmin": 4, "size_arcmin_minor": 4,
     "constellation": 'Cassiopeia', "season": 'Autumn', "difficulty": 'Moderate',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Compact cluster in Cassiopeia.'},
    {"name": 'Open Cluster', "catalog_id": 'C10', "alt_catalog_ids": 'NGC 663',
     "target_type": 'Open Cluster', "ra_hours": 1.7667, "dec_degrees": 61.25,
     "magnitude": 7.1, "size_arcmin": 16, "size_arcmin_minor": 16,
     "constellation": 'Cassiopeia', "season": 'Autumn', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Rich open cluster in Cassiopeia.'},
    {"name": 'Owl Cluster', "catalog_id": 'C13', "alt_catalog_ids": 'NGC 457',
     "target_type": 'Open Cluster', "ra_hours": 1.3183, "dec_degrees": 58.33,
     "magnitude": 6.4, "size_arcmin": 13, "size_arcmin_minor": 13,
     "constellation": 'Cassiopeia', "season": 'Autumn', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Also called the ET Cluster. Two bright eyes with wings.'},
    {"name": 'Double Cluster', "catalog_id": 'C14', "alt_catalog_ids": 'NGC 869/884',
     "target_type": 'Open Cluster', "ra_hours": 2.3667, "dec_degrees": 57.13,
     "magnitude": 4.3, "size_arcmin": 60, "size_arcmin_minor": 30,
     "constellation": 'Perseus', "season": 'Winter', "difficulty": 'Easy',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Spectacular pair of open clusters visible to the naked eye.'},
    {"name": 'Blinking Planetary', "catalog_id": 'C15', "alt_catalog_ids": 'NGC 6826',
     "target_type": 'Planetary Nebula', "ra_hours": 19.7467, "dec_degrees": 50.53,
     "magnitude": 8.8, "size_arcmin": 0.4, "size_arcmin_minor": 0.4,
     "constellation": 'Cygnus', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": True, "broadband_target": False,
     "description": 'Appears to blink when switching between direct and averted vision.'},
    {"name": 'Spiral Galaxy', "catalog_id": 'C17', "alt_catalog_ids": 'NGC 147',
     "target_type": 'Elliptical Galaxy', "ra_hours": 0.5533, "dec_degrees": 48.51,
     "magnitude": 9.5, "size_arcmin": 13, "size_arcmin_minor": 8,
     "constellation": 'Cassiopeia', "season": 'Autumn', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Dwarf spheroidal satellite of M31.'},
    {"name": 'Spiral Galaxy', "catalog_id": 'C18', "alt_catalog_ids": 'NGC 185',
     "target_type": 'Elliptical Galaxy', "ra_hours": 0.6494, "dec_degrees": 48.34,
     "magnitude": 9.2, "size_arcmin": 12, "size_arcmin_minor": 10,
     "constellation": 'Cassiopeia', "season": 'Autumn', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Dwarf elliptical satellite of M31. Contains young blue stars.'},
    {"name": 'Blue Snowball', "catalog_id": 'C22', "alt_catalog_ids": 'NGC 7662',
     "target_type": 'Planetary Nebula', "ra_hours": 23.4317, "dec_degrees": 42.53,
     "magnitude": 8.3, "size_arcmin": 0.5, "size_arcmin_minor": 0.5,
     "constellation": 'Andromeda', "season": 'Autumn', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": True, "broadband_target": False,
     "description": 'Bright compact planetary nebula with vivid blue-green color.'},
    {"name": 'Perseus A', "catalog_id": 'C24', "alt_catalog_ids": 'NGC 1275',
     "target_type": 'Elliptical Galaxy', "ra_hours": 3.33, "dec_degrees": 41.51,
     "magnitude": 11.6, "size_arcmin": 3, "size_arcmin_minor": 2,
     "constellation": 'Perseus', "season": 'Winter', "difficulty": 'Hard',
     "recommended_min_hours": 5, "narrowband_target": False, "broadband_target": True,
     "description": 'Seyfert galaxy at center of the Perseus Cluster.'},
    {"name": 'Intergalactic Tramp', "catalog_id": 'C25', "alt_catalog_ids": 'NGC 2419',
     "target_type": 'Globular Cluster', "ra_hours": 7.6358, "dec_degrees": 38.88,
     "magnitude": 10.4, "size_arcmin": 4, "size_arcmin_minor": 4,
     "constellation": 'Lynx', "season": 'Winter', "difficulty": 'Hard',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Most distant Milky Way globular cluster.'},
    {"name": 'Spiral Galaxy', "catalog_id": 'C26', "alt_catalog_ids": 'NGC 4244',
     "target_type": 'Spiral Galaxy', "ra_hours": 12.2917, "dec_degrees": 37.81,
     "magnitude": 10.2, "size_arcmin": 16, "size_arcmin_minor": 2,
     "constellation": 'Canes Venatici', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 4, "narrowband_target": False, "broadband_target": True,
     "description": 'Edge-on silver needle galaxy.'},
    {"name": 'Crescent Nebula', "catalog_id": 'C27', "alt_catalog_ids": 'NGC 6888',
     "target_type": 'Emission Nebula', "ra_hours": 20.2019, "dec_degrees": 38.35,
     "magnitude": 7.4, "size_arcmin": 18, "size_arcmin_minor": 12,
     "constellation": 'Cygnus', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 6, "narrowband_target": True, "broadband_target": False,
     "description": 'Wind-blown shell around Wolf-Rayet star WR 136.'},
    {"name": 'Open Cluster', "catalog_id": 'C28', "alt_catalog_ids": 'NGC 752',
     "target_type": 'Open Cluster', "ra_hours": 1.9633, "dec_degrees": 37.68,
     "magnitude": 5.7, "size_arcmin": 50, "size_arcmin_minor": 50,
     "constellation": 'Andromeda', "season": 'Autumn', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Large old open cluster.'},
    {"name": 'Spiral Galaxy', "catalog_id": 'C29', "alt_catalog_ids": 'NGC 5005',
     "target_type": 'Spiral Galaxy', "ra_hours": 13.1822, "dec_degrees": 37.06,
     "magnitude": 9.8, "size_arcmin": 6, "size_arcmin_minor": 3,
     "constellation": 'Canes Venatici', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Inclined spiral with a bright nucleus.'},
    {"name": 'Spiral Galaxy', "catalog_id": 'C30', "alt_catalog_ids": 'NGC 7331',
     "target_type": 'Spiral Galaxy', "ra_hours": 22.6178, "dec_degrees": 34.42,
     "magnitude": 9.5, "size_arcmin": 11, "size_arcmin_minor": 4,
     "constellation": 'Pegasus', "season": 'Autumn', "difficulty": 'Moderate',
     "recommended_min_hours": 4, "narrowband_target": False, "broadband_target": True,
     "description": 'Bright unbarred spiral often compared to the Milky Way.'},
    {"name": 'Flaming Star Nebula', "catalog_id": 'C31', "alt_catalog_ids": 'IC 405',
     "target_type": 'Emission Nebula', "ra_hours": 5.27, "dec_degrees": 34.28,
     "magnitude": None, "size_arcmin": 37, "size_arcmin_minor": 19,
     "constellation": 'Auriga', "season": 'Winter', "difficulty": 'Moderate',
     "recommended_min_hours": 5, "narrowband_target": True, "broadband_target": True,
     "description": 'Emission/reflection nebula around runaway star AE Aurigae.'},
    {"name": 'Whale Galaxy', "catalog_id": 'C32', "alt_catalog_ids": 'NGC 4631',
     "target_type": 'Spiral Galaxy', "ra_hours": 12.7022, "dec_degrees": 32.54,
     "magnitude": 9.2, "size_arcmin": 15, "size_arcmin_minor": 3,
     "constellation": 'Canes Venatici', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 4, "narrowband_target": False, "broadband_target": True,
     "description": 'Edge-on spiral with small companion NGC 4627.'},
    {"name": 'East Veil Nebula', "catalog_id": 'C33', "alt_catalog_ids": 'NGC 6992',
     "target_type": 'Supernova Remnant', "ra_hours": 20.94, "dec_degrees": 31.72,
     "magnitude": 7.0, "size_arcmin": 60, "size_arcmin_minor": 8,
     "constellation": 'Cygnus', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 5, "narrowband_target": True, "broadband_target": True,
     "description": 'Eastern arc of the Cygnus Loop supernova remnant.'},
    {"name": 'West Veil Nebula', "catalog_id": 'C34', "alt_catalog_ids": 'NGC 6960',
     "target_type": 'Supernova Remnant', "ra_hours": 20.7606, "dec_degrees": 30.71,
     "magnitude": 7.0, "size_arcmin": 70, "size_arcmin_minor": 6,
     "constellation": 'Cygnus', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 5, "narrowband_target": True, "broadband_target": True,
     "description": 'Western arc of the Veil near 52 Cygni.'},
    {"name": 'Spiral Galaxy', "catalog_id": 'C35', "alt_catalog_ids": 'NGC 4889',
     "target_type": 'Elliptical Galaxy', "ra_hours": 13.0022, "dec_degrees": 27.98,
     "magnitude": 11.5, "size_arcmin": 3, "size_arcmin_minor": 2,
     "constellation": 'Coma Berenices', "season": 'Spring', "difficulty": 'Hard',
     "recommended_min_hours": 5, "narrowband_target": False, "broadband_target": True,
     "description": 'Supergiant elliptical at the heart of the Coma Cluster.'},
    {"name": 'Spiral Galaxy', "catalog_id": 'C36', "alt_catalog_ids": 'NGC 4559',
     "target_type": 'Spiral Galaxy', "ra_hours": 12.6, "dec_degrees": 27.96,
     "magnitude": 9.9, "size_arcmin": 11, "size_arcmin_minor": 5,
     "constellation": 'Coma Berenices', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Face-on spiral in the Coma I cloud.'},
    {"name": 'Open Cluster', "catalog_id": 'C37', "alt_catalog_ids": 'NGC 6885',
     "target_type": 'Open Cluster', "ra_hours": 20.2, "dec_degrees": 26.48,
     "magnitude": 5.7, "size_arcmin": 7, "size_arcmin_minor": 7,
     "constellation": 'Vulpecula', "season": 'Summer', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Open cluster near M27 Dumbbell Nebula.'},
    {"name": 'Needle Galaxy', "catalog_id": 'C38', "alt_catalog_ids": 'NGC 4565',
     "target_type": 'Spiral Galaxy', "ra_hours": 12.6058, "dec_degrees": 25.99,
     "magnitude": 9.6, "size_arcmin": 16, "size_arcmin_minor": 2,
     "constellation": 'Coma Berenices', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 4, "narrowband_target": False, "broadband_target": True,
     "description": 'Classic edge-on spiral with a prominent dust lane.'},
    {"name": 'Eskimo Nebula', "catalog_id": 'C39', "alt_catalog_ids": 'NGC 2392',
     "target_type": 'Planetary Nebula', "ra_hours": 7.4864, "dec_degrees": 20.91,
     "magnitude": 9.2, "size_arcmin": 0.8, "size_arcmin_minor": 0.8,
     "constellation": 'Gemini', "season": 'Winter', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": True, "broadband_target": False,
     "description": 'Double-shelled planetary with a face-like appearance.'},
    {"name": 'Hyades', "catalog_id": 'C41', "alt_catalog_ids": 'Melotte 25',
     "target_type": 'Open Cluster', "ra_hours": 4.45, "dec_degrees": 15.87,
     "magnitude": 0.5, "size_arcmin": 330, "size_arcmin_minor": 330,
     "constellation": 'Taurus', "season": 'Winter', "difficulty": 'Easy',
     "recommended_min_hours": 1, "narrowband_target": False, "broadband_target": True,
     "description": 'Nearest open cluster. The V shape of Taurus.'},
    {"name": "Hubble's Variable Nebula", "catalog_id": 'C46', "alt_catalog_ids": 'NGC 2261',
     "target_type": 'Reflection Nebula', "ra_hours": 6.6528, "dec_degrees": 8.73,
     "magnitude": 10.0, "size_arcmin": 2, "size_arcmin_minor": 1,
     "constellation": 'Monoceros', "season": 'Winter', "difficulty": 'Hard',
     "recommended_min_hours": 4, "narrowband_target": False, "broadband_target": True,
     "description": 'Fan-shaped nebula that changes appearance over weeks.'},
    {"name": 'Star Cluster', "catalog_id": 'C47', "alt_catalog_ids": 'NGC 6934',
     "target_type": 'Globular Cluster', "ra_hours": 20.57, "dec_degrees": 7.4,
     "magnitude": 8.9, "size_arcmin": 6, "size_arcmin_minor": 6,
     "constellation": 'Delphinus', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Globular cluster in Delphinus.'},
    {"name": 'Spindle Galaxy', "catalog_id": 'C53', "alt_catalog_ids": 'NGC 3115',
     "target_type": 'Elliptical Galaxy', "ra_hours": 10.0872, "dec_degrees": -7.72,
     "magnitude": 8.9, "size_arcmin": 7, "size_arcmin_minor": 2,
     "constellation": 'Sextans', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": False, "broadband_target": True,
     "description": 'Edge-on lenticular with a massive black hole.'},
    {"name": 'Saturn Nebula', "catalog_id": 'C55', "alt_catalog_ids": 'NGC 7009',
     "target_type": 'Planetary Nebula', "ra_hours": 21.0697, "dec_degrees": -11.37,
     "magnitude": 8.0, "size_arcmin": 0.4, "size_arcmin_minor": 0.4,
     "constellation": 'Aquarius', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 3, "narrowband_target": True, "broadband_target": False,
     "description": 'Named for Saturn-like extensions. Beautiful green hue.'},
    {"name": "Barnard's Galaxy", "catalog_id": 'C57', "alt_catalog_ids": 'NGC 6822',
     "target_type": 'Irregular Galaxy', "ra_hours": 19.7489, "dec_degrees": -14.8,
     "magnitude": 8.7, "size_arcmin": 16, "size_arcmin_minor": 14,
     "constellation": 'Sagittarius', "season": 'Summer', "difficulty": 'Hard',
     "recommended_min_hours": 4, "narrowband_target": False, "broadband_target": True,
     "description": 'Nearby dwarf irregular in the Local Group.'},
    {"name": 'Sculptor Galaxy', "catalog_id": 'C65', "alt_catalog_ids": 'NGC 253',
     "target_type": 'Spiral Galaxy', "ra_hours": 0.7925, "dec_degrees": -25.29,
     "magnitude": 7.2, "size_arcmin": 28, "size_arcmin_minor": 7,
     "constellation": 'Sculptor', "season": 'Autumn', "difficulty": 'Moderate',
     "recommended_min_hours": 4, "narrowband_target": False, "broadband_target": True,
     "description": 'One of the brightest galaxies beyond the Local Group. Edge-on starburst.'},
    {"name": 'Centaurus A', "catalog_id": 'C77', "alt_catalog_ids": 'NGC 5128',
     "target_type": 'Elliptical Galaxy', "ra_hours": 13.4244, "dec_degrees": -43.02,
     "magnitude": 6.8, "size_arcmin": 26, "size_arcmin_minor": 20,
     "constellation": 'Centaurus', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 4, "narrowband_target": False, "broadband_target": True,
     "description": 'Nearest giant radio galaxy. Dramatic dark dust lane.'},
    {"name": 'Omega Centauri', "catalog_id": 'C80', "alt_catalog_ids": 'NGC 5139',
     "target_type": 'Globular Cluster', "ra_hours": 13.4461, "dec_degrees": -47.48,
     "magnitude": 3.7, "size_arcmin": 36, "size_arcmin_minor": 36,
     "constellation": 'Centaurus', "season": 'Spring', "difficulty": 'Easy',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Largest and brightest globular in the Milky Way. Millions of stars.'},
    {"name": '47 Tucanae', "catalog_id": 'C106', "alt_catalog_ids": 'NGC 104',
     "target_type": 'Globular Cluster', "ra_hours": 0.4017, "dec_degrees": -72.08,
     "magnitude": 4.0, "size_arcmin": 31, "size_arcmin_minor": 31,
     "constellation": 'Tucana', "season": 'Autumn', "difficulty": 'Easy',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Second-finest globular. Appears near the Small Magellanic Cloud.'},
    {"name": 'Sh2-132 Lion Nebula', "catalog_id": 'Sh2-132', "alt_catalog_ids": '',
     "target_type": 'Emission Nebula', "ra_hours": 22.3192, "dec_degrees": 56.08,
     "magnitude": None, "size_arcmin": 40, "size_arcmin_minor": 30,
     "constellation": 'Cepheus', "season": 'Autumn', "difficulty": 'Hard',
     "recommended_min_hours": 8, "narrowband_target": True, "broadband_target": False,
     "description": 'Faint emission nebula resembling a lion. Beautiful in SHO palette.'},
    {"name": 'Spider Nebula', "catalog_id": 'IC 417', "alt_catalog_ids": 'Sh2-234',
     "target_type": 'Emission Nebula', "ra_hours": 5.4683, "dec_degrees": 34.42,
     "magnitude": None, "size_arcmin": 25, "size_arcmin_minor": 25,
     "constellation": 'Auriga', "season": 'Winter', "difficulty": 'Hard',
     "recommended_min_hours": 6, "narrowband_target": True, "broadband_target": False,
     "description": 'Emission nebula with open cluster Stock 8.'},
    {"name": 'Lobster Claw Nebula', "catalog_id": 'Sh2-157', "alt_catalog_ids": '',
     "target_type": 'Emission Nebula', "ra_hours": 23.2681, "dec_degrees": 60.02,
     "magnitude": None, "size_arcmin": 60, "size_arcmin_minor": 50,
     "constellation": 'Cassiopeia', "season": 'Autumn', "difficulty": 'Hard',
     "recommended_min_hours": 8, "narrowband_target": True, "broadband_target": False,
     "description": 'Large faint emission nebula near the Bubble Nebula.'},
    {"name": 'Cederblad 214', "catalog_id": 'Ced 214', "alt_catalog_ids": 'Sh2-171',
     "target_type": 'Emission Nebula', "ra_hours": 0.0567, "dec_degrees": 67.17,
     "magnitude": None, "size_arcmin": 40, "size_arcmin_minor": 30,
     "constellation": 'Cepheus', "season": 'Autumn', "difficulty": 'Hard',
     "recommended_min_hours": 8, "narrowband_target": True, "broadband_target": False,
     "description": 'Bright HII region inside the larger Sh2-171.'},
    {"name": 'Propeller Nebula', "catalog_id": 'DWB 111', "alt_catalog_ids": 'Simeis 57',
     "target_type": 'Emission Nebula', "ra_hours": 20.2667, "dec_degrees": 43.67,
     "magnitude": None, "size_arcmin": 15, "size_arcmin_minor": 6,
     "constellation": 'Cygnus', "season": 'Summer', "difficulty": 'Hard',
     "recommended_min_hours": 8, "narrowband_target": True, "broadband_target": False,
     "description": 'Faint propeller-shaped emission nebula in Cygnus.'},
    {"name": 'Soap Bubble Nebula', "catalog_id": 'PNG 75.5+1.7', "alt_catalog_ids": 'PN G75.5+1.7',
     "target_type": 'Planetary Nebula', "ra_hours": 20.2617, "dec_degrees": 38.72,
     "magnitude": None, "size_arcmin": 4, "size_arcmin_minor": 4,
     "constellation": 'Cygnus', "season": 'Summer', "difficulty": 'Hard',
     "recommended_min_hours": 8, "narrowband_target": True, "broadband_target": False,
     "description": 'Extremely faint spherical planetary. Discovered by amateur in 2008.'},
    {"name": 'Medusa Nebula', "catalog_id": 'Abell 21', "alt_catalog_ids": 'Sh2-274',
     "target_type": 'Planetary Nebula', "ra_hours": 7.4839, "dec_degrees": 13.23,
     "magnitude": None, "size_arcmin": 10, "size_arcmin_minor": 10,
     "constellation": 'Gemini', "season": 'Winter', "difficulty": 'Hard',
     "recommended_min_hours": 8, "narrowband_target": True, "broadband_target": False,
     "description": 'Large ancient planetary nebula with jellyfish-like filaments.'},
    {"name": 'Rho Ophiuchi Complex', "catalog_id": 'Rho Oph', "alt_catalog_ids": 'IC 4604',
     "target_type": 'Reflection Nebula', "ra_hours": 16.4264, "dec_degrees": -23.45,
     "magnitude": None, "size_arcmin": 240, "size_arcmin_minor": 240,
     "constellation": 'Ophiuchus', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 5, "narrowband_target": False, "broadband_target": True,
     "description": 'Closest star-forming region. Rich mix of emission, reflection, dark nebulae.'},
    {"name": "Markarian's Chain", "catalog_id": 'Markarian Chain', "alt_catalog_ids": 'M84 M86 NGC 4435 NGC 4438',
     "target_type": 'Galaxy Group', "ra_hours": 12.45, "dec_degrees": 13.17,
     "magnitude": 9.0, "size_arcmin": 60, "size_arcmin_minor": 10,
     "constellation": 'Virgo', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 4, "narrowband_target": False, "broadband_target": True,
     "description": 'Spectacular chain of galaxies forming a graceful arc in the Virgo Cluster.'},
    {"name": 'Antennae Galaxies', "catalog_id": 'NGC 4038/4039', "alt_catalog_ids": 'Caldwell 60/61',
     "target_type": 'Galaxy Group', "ra_hours": 12.0314, "dec_degrees": -18.88,
     "magnitude": 10.3, "size_arcmin": 5, "size_arcmin_minor": 3,
     "constellation": 'Corvus', "season": 'Spring', "difficulty": 'Hard',
     "recommended_min_hours": 5, "narrowband_target": False, "broadband_target": True,
     "description": 'Famous pair of interacting/merging galaxies with tidal tails.'},
    {"name": "Stephan's Quintet", "catalog_id": 'HCG 92', "alt_catalog_ids": 'NGC 7317-7320',
     "target_type": 'Galaxy Group', "ra_hours": 22.5994, "dec_degrees": 33.97,
     "magnitude": 13.0, "size_arcmin": 3, "size_arcmin_minor": 3,
     "constellation": 'Pegasus', "season": 'Autumn', "difficulty": 'Hard',
     "recommended_min_hours": 6, "narrowband_target": False, "broadband_target": True,
     "description": "Compact galaxy group featured in JWST's first images."},
    {"name": 'Embryo Nebula', "catalog_id": 'NGC 1333', "alt_catalog_ids": '',
     "target_type": 'Reflection Nebula', "ra_hours": 3.4861, "dec_degrees": 31.35,
     "magnitude": None, "size_arcmin": 6, "size_arcmin_minor": 3,
     "constellation": 'Perseus', "season": 'Winter', "difficulty": 'Hard',
     "recommended_min_hours": 6, "narrowband_target": False, "broadband_target": True,
     "description": 'Active star-forming region with Herbig-Haro objects.'},
    {"name": 'Spaghetti Nebula', "catalog_id": 'Sh2-240', "alt_catalog_ids": 'Simeis 147',
     "target_type": 'Supernova Remnant', "ra_hours": 5.65, "dec_degrees": 28.0,
     "magnitude": None, "size_arcmin": 180, "size_arcmin_minor": 180,
     "constellation": 'Taurus', "season": 'Winter', "difficulty": 'Hard',
     "recommended_min_hours": 15, "narrowband_target": True, "broadband_target": False,
     "description": 'Enormous extremely faint SNR. Ultimate narrowband challenge.'},
    {"name": 'Fossil Footprint', "catalog_id": 'NGC 1491', "alt_catalog_ids": 'Sh2-206',
     "target_type": 'Emission Nebula', "ra_hours": 4.0539, "dec_degrees": 51.32,
     "magnitude": None, "size_arcmin": 3, "size_arcmin_minor": 3,
     "constellation": 'Perseus', "season": 'Winter', "difficulty": 'Hard',
     "recommended_min_hours": 6, "narrowband_target": True, "broadband_target": False,
     "description": 'Compact emission nebula energized by a single star.'},
    {"name": 'Elephant Trunk Detail', "catalog_id": 'IC 1396A', "alt_catalog_ids": 'vdB 142',
     "target_type": 'Emission Nebula', "ra_hours": 21.6494, "dec_degrees": 57.5,
     "magnitude": None, "size_arcmin": 20, "size_arcmin_minor": 12,
     "constellation": 'Cepheus', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 6, "narrowband_target": True, "broadband_target": False,
     "description": 'Dark globule and rim within the larger IC 1396 complex.'},
    {"name": 'Flying Bat Nebula', "catalog_id": 'Sh2-129', "alt_catalog_ids": '',
     "target_type": 'Emission Nebula', "ra_hours": 21.1931, "dec_degrees": 59.97,
     "magnitude": None, "size_arcmin": 200, "size_arcmin_minor": 120,
     "constellation": 'Cepheus', "season": 'Summer', "difficulty": 'Hard',
     "recommended_min_hours": 8, "narrowband_target": True, "broadband_target": False,
     "description": 'Very large faint emission nebula containing the Squid Nebula (Ou4).'},
    {"name": 'Squid Nebula', "catalog_id": 'Ou4', "alt_catalog_ids": '',
     "target_type": 'Planetary Nebula', "ra_hours": 21.1964, "dec_degrees": 59.98,
     "magnitude": None, "size_arcmin": 60, "size_arcmin_minor": 20,
     "constellation": 'Cepheus', "season": 'Summer', "difficulty": 'Hard',
     "recommended_min_hours": 15, "narrowband_target": True, "broadband_target": False,
     "description": 'Giant bipolar outflow inside Sh2-129. Extremely faint, needs heavy OIII.'},
    {"name": 'Tulip Nebula', "catalog_id": 'Sh2-101', "alt_catalog_ids": '',
     "target_type": 'Emission Nebula', "ra_hours": 19.9933, "dec_degrees": 35.3,
     "magnitude": None, "size_arcmin": 16, "size_arcmin_minor": 9,
     "constellation": 'Cygnus', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 6, "narrowband_target": True, "broadband_target": False,
     "description": 'Flower-shaped nebula near Cygnus X-1 black hole candidate.'},
    {"name": 'Gamma Cygni Nebula', "catalog_id": 'IC 1318', "alt_catalog_ids": 'Sh2-108',
     "target_type": 'Emission Nebula', "ra_hours": 20.3706, "dec_degrees": 40.26,
     "magnitude": None, "size_arcmin": 60, "size_arcmin_minor": 60,
     "constellation": 'Cygnus', "season": 'Summer', "difficulty": 'Moderate',
     "recommended_min_hours": 5, "narrowband_target": True, "broadband_target": False,
     "description": 'Complex emission nebula surrounding Sadr.'},
    {"name": 'Skull Nebula', "catalog_id": 'NGC 246', "alt_catalog_ids": 'Caldwell 56',
     "target_type": 'Planetary Nebula', "ra_hours": 0.7839, "dec_degrees": -11.88,
     "magnitude": 8.0, "size_arcmin": 4, "size_arcmin_minor": 4,
     "constellation": 'Cetus', "season": 'Autumn', "difficulty": 'Moderate',
     "recommended_min_hours": 4, "narrowband_target": True, "broadband_target": False,
     "description": 'Large planetary with skull-like appearance in OIII.'},
    {"name": 'Ghost of Cassiopeia', "catalog_id": 'IC 63', "alt_catalog_ids": '',
     "target_type": 'Reflection Nebula', "ra_hours": 0.9914, "dec_degrees": 60.9,
     "magnitude": None, "size_arcmin": 10, "size_arcmin_minor": 3,
     "constellation": 'Cassiopeia', "season": 'Autumn', "difficulty": 'Hard',
     "recommended_min_hours": 6, "narrowband_target": True, "broadband_target": True,
     "description": 'Ghostly nebula illuminated by Gamma Cassiopeiae.'},
    {"name": "Pickering's Triangle", "catalog_id": 'Pickering Tri', "alt_catalog_ids": 'Simeis 3-188',
     "target_type": 'Supernova Remnant', "ra_hours": 20.8578, "dec_degrees": 31.71,
     "magnitude": None, "size_arcmin": 45, "size_arcmin_minor": 15,
     "constellation": 'Cygnus', "season": 'Summer', "difficulty": 'Hard',
     "recommended_min_hours": 8, "narrowband_target": True, "broadband_target": False,
     "description": 'Faint wispy section of the Veil Nebula.'},
    {"name": 'NGC 2903', "catalog_id": 'NGC 2903', "alt_catalog_ids": '',
     "target_type": 'Spiral Galaxy', "ra_hours": 9.5361, "dec_degrees": 21.5,
     "magnitude": 9.0, "size_arcmin": 13, "size_arcmin_minor": 6,
     "constellation": 'Leo', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 4, "narrowband_target": False, "broadband_target": True,
     "description": 'Bright barred spiral overlooked by Messier.'},
    {"name": 'Hamburger Galaxy', "catalog_id": 'NGC 3628', "alt_catalog_ids": 'Arp 317',
     "target_type": 'Spiral Galaxy', "ra_hours": 11.3381, "dec_degrees": 13.59,
     "magnitude": 9.5, "size_arcmin": 15, "size_arcmin_minor": 4,
     "constellation": 'Leo', "season": 'Spring', "difficulty": 'Moderate',
     "recommended_min_hours": 4, "narrowband_target": False, "broadband_target": True,
     "description": 'Edge-on spiral with tidal tail. Leo Triplet member with M65/M66.'},
    {"name": 'NGC 3718', "catalog_id": 'NGC 3718', "alt_catalog_ids": 'Arp 214',
     "target_type": 'Spiral Galaxy', "ra_hours": 11.5431, "dec_degrees": 53.07,
     "magnitude": 10.6, "size_arcmin": 8, "size_arcmin_minor": 4,
     "constellation": 'Ursa Major', "season": 'Spring', "difficulty": 'Hard',
     "recommended_min_hours": 5, "narrowband_target": False, "broadband_target": True,
     "description": 'Warped spiral with S-shaped dust lane.'},
    {"name": 'Rose Galaxies', "catalog_id": 'UGC 1810', "alt_catalog_ids": 'Arp 273',
     "target_type": 'Galaxy Group', "ra_hours": 2.3581, "dec_degrees": 39.36,
     "magnitude": 12.8, "size_arcmin": 2, "size_arcmin_minor": 1,
     "constellation": 'Andromeda', "season": 'Winter', "difficulty": 'Hard',
     "recommended_min_hours": 6, "narrowband_target": False, "broadband_target": True,
     "description": 'Interacting pair resembling a rose. HST anniversary image.'},
    {"name": 'Abell 85', "catalog_id": 'Abell 85', "alt_catalog_ids": 'CTB 1',
     "target_type": 'Supernova Remnant', "ra_hours": 23.9858, "dec_degrees": 62.44,
     "magnitude": None, "size_arcmin": 35, "size_arcmin_minor": 35,
     "constellation": 'Cassiopeia', "season": 'Autumn', "difficulty": 'Hard',
     "recommended_min_hours": 10, "narrowband_target": True, "broadband_target": False,
     "description": 'Large faint SNR. Circular shell best in Halpha and OIII.'},
    {"name": 'NGC 1532', "catalog_id": 'NGC 1532', "alt_catalog_ids": '',
     "target_type": 'Spiral Galaxy', "ra_hours": 4.2011, "dec_degrees": -32.87,
     "magnitude": 9.9, "size_arcmin": 11, "size_arcmin_minor": 3,
     "constellation": 'Eridanus', "season": 'Winter', "difficulty": 'Moderate',
     "recommended_min_hours": 4, "narrowband_target": False, "broadband_target": True,
     "description": 'Edge-on spiral interacting with NGC 1531.'},
    {"name": 'NGC 2158', "catalog_id": 'NGC 2158', "alt_catalog_ids": '',
     "target_type": 'Open Cluster', "ra_hours": 6.1239, "dec_degrees": 24.1,
     "magnitude": 8.6, "size_arcmin": 5, "size_arcmin_minor": 5,
     "constellation": 'Gemini', "season": 'Winter', "difficulty": 'Moderate',
     "recommended_min_hours": 2, "narrowband_target": False, "broadband_target": True,
     "description": 'Rich distant open cluster. Great contrast when paired with M35.'},
    {"name": 'Cigar Galaxy', "catalog_id": 'NGC 3034', "alt_catalog_ids": 'M82',
     "target_type": 'Irregular Galaxy', "ra_hours": 9.9311, "dec_degrees": 69.68,
     "magnitude": 8.4, "size_arcmin": 11, "size_arcmin_minor": 4,
     "constellation": 'Ursa Major', "season": 'Spring', "difficulty": 'Easy',
     "recommended_min_hours": 3, "narrowband_target": True, "broadband_target": True,
     "description": 'Starburst galaxy with dramatic Halpha outflows.'},
    {"name": 'Blue Horsehead', "catalog_id": 'IC 4592', "alt_catalog_ids": '',
     "target_type": 'Reflection Nebula', "ra_hours": 16.2006, "dec_degrees": -19.46,
     "magnitude": None, "size_arcmin": 90, "size_arcmin_minor": 60,
     "constellation": 'Scorpius', "season": 'Summer', "difficulty": 'Hard',
     "recommended_min_hours": 5, "narrowband_target": False, "broadband_target": True,
     "description": "Faint reflection nebula shaped like a horse's head in blue light."},
]
